import {
  AlertDemo,
  AccordionDemo,
  BooleanControlsDemo,
  ButtonsDemo,
  CardDemo,
  ChartsDemo,
  DialogDemo,
  DrawerDemo,
  IconsDemo,
  IdentityDemo,
  ImageGridDemo,
  NavigationDemo,
  OverlayBlocksDemo,
  ProgressDemo,
  SelectsDemo,
  StateDemo,
  TablesDemo,
  TextFieldsDemo,
  TooltipDemo,
  WorkspaceBlocksDemo,
} from '../showcaseRegistry'
import type { DocEntry } from './types'

function entry(input: Omit<DocEntry, 'status'> & { status?: DocEntry['status'] }): DocEntry {
  return { status: 'ready', ...input }
}

export const componentDocs: DocEntry[] = [
  entry({
    id: 'button',
    section: 'components',
    group: 'inputs',
    title: 'Button',
    summary: '가장 기본적인 action trigger다. primary, secondary, accent, icon action을 한 규칙으로 제공한다.',
    whenToUse: '저장, 생성, 이동, 열기처럼 명확한 action이 필요할 때 사용한다.',
    whenNotToUse: '단순 navigation 링크, tag, passive label 용도로 쓰지 않는다.',
    importPath: "import { Button, IconButton } from '@ingradient/ui/components'",
    examples: [{ title: 'Primary and secondary actions', description: 'Primary, secondary, accent, disabled, and icon actions.', component: ButtonsDemo }],
    states: ['default', 'hover', 'disabled'],
    props: [
      { name: 'variant', type: "'solid' | 'secondary' | 'accent'", required: false, defaultValue: 'solid', description: '행동의 강조 단계를 정한다.' },
      { name: 'size', type: "'sm' | 'md' | 'lg'", required: false, defaultValue: 'md', description: '버튼 높이와 내부 spacing을 바꾼다.' },
      { name: 'leadingIcon', type: 'ReactNode', required: false, description: '레이블 앞쪽 아이콘을 넣는다.' },
      { name: 'trailingIcon', type: 'ReactNode', required: false, description: '레이블 뒤쪽 아이콘을 넣는다.' },
      { name: 'children', type: 'ReactNode', required: true, description: '버튼 레이블 또는 커스텀 콘텐츠다.' },
    ],
    variants: [
      { name: 'variant', values: ['solid', 'secondary', 'accent'], description: '행동 우선순위에 따라 시각 강조를 바꾼다.' },
      { name: 'size', values: ['sm', 'md', 'lg'], description: '폼 밀도와 화면 맥락에 따라 버튼 높이를 조정한다.' },
    ],
    related: ['text-field', 'toolbar', 'dialog'],
    notes: ['새 버튼 스타일을 feature 안에서 만들기보다 variant를 확장할지 먼저 검토한다.'],
    dos: ['주요 action은 Button variant로 통일한다.', '아이콘만 있는 action은 IconButton을 쓴다.'],
    donts: ['텍스트 링크를 버튼처럼 꾸며서 대체하지 않는다.', 'destructive flow를 accent variant로 처리하지 않는다.'],
  }),
  entry({
    id: 'text-field',
    section: 'components',
    group: 'inputs',
    title: 'Text Field',
    summary: 'single-line, search, textarea, number, password 입력을 같은 control contract로 제공한다.',
    whenToUse: '폼과 필터에서 문자열 또는 숫자 입력이 필요할 때 사용한다.',
    whenNotToUse: '선택지가 정해진 값을 받는 경우에는 select 계열을 먼저 고려한다.',
    importPath: "import { TextField, SearchField, TextareaField, NumberField, PasswordField } from '@ingradient/ui/components'",
    examples: [{ title: 'Common text inputs', description: 'Single-line, search, and multiline input controls.', component: TextFieldsDemo }],
    states: ['default', 'focus', 'disabled', 'multiline'],
    props: [
      { name: 'placeholder', type: 'string', required: false, description: '입력 힌트를 표시한다.' },
      { name: 'value', type: 'string', required: false, description: 'controlled input 값을 전달한다.' },
      { name: 'onChange', type: '(event) => void', required: false, description: '입력 변경을 처리한다.' },
      { name: 'disabled', type: 'boolean', required: false, defaultValue: 'false', description: '입력을 비활성화한다.' },
      { name: 'rows', type: 'number', required: false, description: 'TextareaField 행 수를 지정한다.' },
    ],
    variants: [
      { name: 'field type', values: ['text', 'search', 'textarea', 'number', 'password'], description: '입력 목적에 따라 같은 visual contract를 유지한다.' },
    ],
    related: ['select', 'form-section'],
    notes: ['TextField 계열은 control recipe를 공유하므로 feature별 새 input shell을 만들지 않는 것이 원칙이다.'],
    dos: ['검색은 SearchField, 장문 입력은 TextareaField를 쓴다.'],
    donts: ['feature별로 다른 border, radius, padding 값을 input에 직접 하드코딩하지 않는다.'],
  }),
  entry({
    id: 'select',
    section: 'components',
    group: 'inputs',
    title: 'Select',
    summary: 'native-like select와 custom dropdown select를 같은 디자인 언어로 제공한다.',
    whenToUse: '선택 가능한 option 집합이 있고, compact한 choice input이 필요할 때 사용한다.',
    whenNotToUse: '복잡한 search/autocomplete workflow를 단순 select로 억지로 처리하지 않는다.',
    importPath: "import { SelectField, DropdownSelect } from '@ingradient/ui/components'",
    examples: [{ title: 'Native-compatible and custom select', description: 'Default select and workspace dropdown examples.', component: SelectsDemo }],
    states: ['default', 'open', 'disabled'],
    props: [
      { name: 'children', type: 'option elements', required: true, description: 'SelectField option 목록이다.' },
      { name: 'value', type: 'string', required: false, description: 'controlled selected value다.' },
      { name: 'defaultValue', type: 'string', required: false, description: 'uncontrolled 초기값이다.' },
      { name: 'onChange', type: '(event) => void | (value) => void', required: false, description: '선택 변경을 처리한다.' },
      { name: 'options', type: 'DropdownOption[]', required: false, description: 'DropdownSelect option 배열이다.' },
    ],
    variants: [
      { name: 'implementation', values: ['SelectField', 'DropdownSelect'], description: 'native form compatibility가 필요한지, richer option UI가 필요한지에 따라 선택한다.' },
    ],
    related: ['text-field', 'toolbar', 'dialog'],
    notes: ['드롭다운 스타일은 custom overlay를 쓰므로 native browser popup에 의존하지 않는다.'],
    dos: ['form submit과 hidden select compatibility가 필요하면 SelectField를 쓴다.'],
    donts: ['긴 설명과 부가 메타를 단순 option 문자열로 욱여넣지 않는다.'],
  }),
  entry({
    id: 'checkbox-switch',
    section: 'components',
    group: 'inputs',
    title: 'Checkbox & Switch',
    summary: 'boolean setting과 opt-in action을 위한 compact control이다.',
    whenToUse: '설정 토글, 다중 선택, 켜짐/꺼짐 상태가 명확한 경우에 사용한다.',
    whenNotToUse: '서로 배타적인 선택지는 radio나 select를 쓰는 것이 더 맞다.',
    importPath: "import { Checkbox, Switch } from '@ingradient/ui/components'",
    examples: [{ title: 'Boolean controls', description: 'Checkbox and switch controls for forms and settings.', component: BooleanControlsDemo }],
    states: ['checked', 'unchecked', 'disabled'],
    props: [
      { name: 'checked', type: 'boolean', required: false, description: 'controlled 상태를 전달한다.' },
      { name: 'defaultChecked', type: 'boolean', required: false, description: 'uncontrolled 초기 상태를 지정한다.' },
      { name: 'onChange', type: '(event) => void', required: false, description: '상태 전환을 처리한다.' },
      { name: 'disabled', type: 'boolean', required: false, defaultValue: 'false', description: '상호작용을 막는다.' },
    ],
    variants: [{ name: 'control type', values: ['Checkbox', 'Switch'], description: '목록 선택인지 설정 토글인지에 따라 control을 고른다.' }],
    related: ['form-section', 'settings-shell'],
    notes: ['같은 boolean이라도 batch selection은 Checkbox, immediate setting은 Switch가 더 읽기 쉽다.'],
    dos: ['boolean 의미를 라벨에서 명확히 쓴다.'],
    donts: ['켜짐/꺼짐 의미가 애매한 문장과 함께 쓰지 않는다.'],
  }),
  entry({
    id: 'avatar-badge',
    section: 'components',
    group: 'data-display',
    title: 'Avatar & Badge',
    summary: 'identity 표시, 작은 metadata pill, lightweight tag에 쓰는 compact display set이다.',
    whenToUse: 'user identity, status tag, small metadata label이 필요할 때 사용한다.',
    whenNotToUse: '브랜드 자산은 Avatar로 대체하지 말고 BrandMark/BrandLogo를 쓴다.',
    importPath: "import { Avatar, Badge, Chip, StatusPill } from '@ingradient/ui/components'",
    examples: [{ title: 'Identity and metadata chips', description: 'Avatar, badge, chip, and status pill examples.', component: IdentityDemo }],
    states: ['default', 'accent', 'success', 'warning'],
    props: [
      { name: 'children', type: 'ReactNode', required: false, description: 'Badge/Chip 안쪽 label이다.' },
      { name: '$tone', type: 'semantic tone', required: false, description: 'Badge 계열의 색상 tone을 바꾼다.' },
      { name: 'src', type: 'string', required: false, description: 'Avatar 이미지 소스다.' },
      { name: 'alt', type: 'string', required: false, description: 'Avatar 대체 텍스트다.' },
    ],
    variants: [
      { name: 'display type', values: ['Avatar', 'Badge', 'Chip', 'StatusPill'], description: 'identity, neutral tag, removable-like chip, semantic status 중 목적에 따라 고른다.' },
    ],
    related: ['brand', 'workspace-blocks'],
    notes: ['brand mark와 avatar는 시각적으로 비슷해 보여도 의미가 다르다.'],
    dos: ['상태에는 StatusPill, 중립 메타에는 Chip/Badge를 쓴다.'],
    donts: ['제품 브랜드 표시를 임의 이니셜 avatar로 대체하지 않는다.'],
  }),
  entry({
    id: 'data-grid',
    section: 'components',
    group: 'data-display',
    title: 'Data Grid',
    summary: '단순 column/row 표현이 필요한 목록, metadata 표, 비교 표의 기본 시작점이다.',
    whenToUse: '서버 데이터나 metadata 목록을 간단한 표로 보여줄 때 사용한다.',
    whenNotToUse: 'inline editing, virtualization, complex pinning이 필요한 고급 grid 역할로 과도하게 확장하지 않는다.',
    importPath: "import { Table, DataGrid } from '@ingradient/ui/components'",
    examples: [{ title: 'Simple table and metadata grid', description: 'Column-driven data table for operational lists.', component: TablesDemo }],
    states: ['default', 'dense', 'empty'],
    props: [
      { name: 'columns', type: 'Array<{ key; header; render }>', required: true, description: '헤더 레이블과 셀 렌더러를 정의한다.' },
      { name: 'rows', type: 'T[]', required: true, description: '행 데이터 배열이다.' },
    ],
    variants: [
      { name: 'alias', values: ['Table', 'DataGrid'], description: '현재 같은 구현을 공유하지만 사용 맥락에 따라 더 읽기 쉬운 이름을 선택한다.' },
    ],
    related: ['progress', 'workspace-blocks', 'settings-shell'],
    notes: ['현재 구현은 intentionally simple하다. sorting, pinning 같은 고급 기능은 core에 넣기 전에 공용성이 충분한지 먼저 본다.'],
    dos: ['표가 단순할수록 Table부터 시작한다.'],
    donts: ['product-specific table behavior를 core table 안에 바로 넣지 않는다.'],
  }),
  entry({
    id: 'image-grid',
    section: 'components',
    group: 'data-display',
    title: 'Image Grid',
    summary: 'thumbnail browsing, selection, metadata chip을 위한 범용 media grid다.',
    whenToUse: 'gallery-like browsing, visual asset list, template preview grid가 필요할 때 사용한다.',
    whenNotToUse: 'annotation, dataset action, export workflow 같은 도메인 semantics를 core image grid에 넣지 않는다.',
    importPath: "import { ImageGrid } from '@ingradient/ui/components'",
    examples: [{ title: 'Reusable thumbnail grid', description: 'Image browsing, selection, and metadata chips.', component: ImageGridDemo }],
    states: ['default', 'selected', 'hover'],
    props: [
      { name: 'items', type: 'T[]', required: true, description: 'grid에 렌더링할 item 목록이다.' },
      { name: 'getImageSrc', type: '(item) => string', required: true, description: 'thumbnail 이미지 경로를 만든다.' },
      { name: 'getTitle', type: '(item) => ReactNode', required: false, description: '카드 제목을 만든다.' },
      { name: 'getDescription', type: '(item) => ReactNode', required: false, description: '카드 설명을 만든다.' },
      { name: 'getMeta', type: '(item) => ReactNode', required: false, description: 'chip이나 metadata row를 추가한다.' },
      { name: 'selectedIds', type: 'Array<string | number>', required: false, description: '선택 상태를 제어한다.' },
      { name: 'onItemClick', type: '(item) => void', required: false, description: '카드 클릭 행동을 정의한다.' },
    ],
    variants: [
      { name: 'card state', values: ['default', 'hover', 'selected'], description: 'hover와 selection affordance를 기본으로 제공한다.' },
      { name: 'minItemWidth', values: ['160+', '180 default', '240+'], description: 'gallery density에 맞춰 카드 최소 폭을 조절한다.' },
    ],
    related: ['data-grid', 'workspace-blocks', 'split-layout'],
    notes: ['이 컴포넌트는 visual browsing shell만 제공한다. dataset/action semantics는 앱이나 domain layer에 남겨야 한다.'],
    dos: ['선택 상태는 `selectedIds`로 외부에서 제어한다.'],
    donts: ['annotation overlay나 export menu를 core image grid 안에 직접 넣지 않는다.'],
  }),
  entry({
    id: 'charts',
    section: 'components',
    group: 'charts',
    title: 'Charts',
    summary: 'metric, trend, distribution 시각화를 위한 chart wrapper와 card 조합이다.',
    whenToUse: 'dashboard, monitoring, analytics에서 일관된 chart skin이 필요할 때 사용한다.',
    whenNotToUse: 'chart-specific business meaning을 wrapper 안에 고정하지 않는다.',
    importPath: "import { ChartContainer, LineChartCard, BarChartCard, PieChartCard } from '@ingradient/ui/components'",
    examples: [{ title: 'Operational chart wrappers', description: 'Line, bar, pie chart cards with shared skin.', component: ChartsDemo }],
    states: ['default', 'loading', 'empty'],
    props: [
      { name: 'title', type: 'string', required: false, description: '카드 타이틀을 표시한다.' },
      { name: 'description', type: 'string', required: false, description: '보조 설명을 표시한다.' },
      { name: 'data', type: 'array', required: true, description: 'chart에 전달할 데이터다.' },
      { name: 'series', type: 'array', required: true, description: 'line/bar/pie mapping을 정의한다.' },
      { name: 'height', type: 'number', required: false, description: 'chart 영역 높이를 지정한다.' },
    ],
    variants: [
      { name: 'chart type', values: ['line', 'bar', 'pie'], description: 'metric 성격에 따라 chart wrapper를 고른다.' },
    ],
    related: ['workspace-blocks', 'dashboard-grid'],
    notes: ['색상과 legend styling은 chart token/variant layer에서 관리한다.'],
    dos: ['같은 metric family는 같은 chart wrapper를 반복 사용한다.'],
    donts: ['page마다 다른 chart skin을 직접 styled-components로 만들지 않는다.'],
  }),
  entry({
    id: 'progress',
    section: 'components',
    group: 'data-display',
    title: 'Progress & Skeleton',
    summary: 'loading placeholder와 progress feedback을 같은 시각 언어로 제공한다.',
    whenToUse: '비동기 로딩, 다운로드 진행률, training/provisioning 진행 상황을 보여줄 때 사용한다.',
    whenNotToUse: '실패 상태를 progress로 감추지 않는다. 실패는 alert나 error state로 분리한다.',
    importPath: "import { ProgressBar, ProgressBlock, Skeleton } from '@ingradient/ui/components'",
    examples: [{ title: 'Loading and progress surfaces', description: 'Progress bar, block, and skeleton placeholders.', component: ProgressDemo }],
    states: ['loading', 'partial', 'complete'],
    props: [
      { name: 'value', type: 'number', required: false, description: '진행률 값을 0~100 기준으로 전달한다.' },
      { name: 'label', type: 'ReactNode', required: false, description: 'ProgressBlock 제목이나 label을 표시한다.' },
      { name: 'height / width', type: 'number | string', required: false, description: 'Skeleton 크기를 지정한다.' },
    ],
    variants: [
      { name: 'display type', values: ['ProgressBar', 'ProgressBlock', 'Skeleton'], description: 'inline, card-like, placeholder 목적에 따라 선택한다.' },
    ],
    related: ['empty-loading', 'alert', 'workspace-blocks'],
    notes: ['로딩과 진행률은 상태 표시다. action 의미를 함께 억지로 넣지 않는다.'],
    dos: ['간단한 loading은 Skeleton, 설명이 필요한 진행은 ProgressBlock을 쓴다.'],
    donts: ['실패 상태를 progress 안에 섞어 표현하지 않는다.'],
  }),
  entry({
    id: 'workspace-blocks',
    section: 'components',
    group: 'data-display',
    title: 'Workspace Blocks',
    summary: 'stat card, assignment row, preview card, hover card, section panel 같은 운영 화면용 블록 묶음이다.',
    whenToUse: 'dashboard, models, training, settings처럼 dense operational surface를 빠르게 조립할 때 사용한다.',
    whenNotToUse: '도메인 의미가 강한 workflow 전체를 단일 block에 숨기지 않는다.',
    importPath: "import { StatCard, MetricCard, AssignmentRow, PreviewCard, HoverCard, SectionPanel, ActionBar } from '@ingradient/ui/components'",
    examples: [{ title: 'Dense operational blocks', description: 'Metric cards, assignment rows, preview cards, action and hover blocks.', component: WorkspaceBlocksDemo }],
    states: ['default', 'preview', 'assignment', 'metric'],
    props: [
      { name: 'title', type: 'ReactNode', required: false, description: 'card 또는 block 제목을 전달한다.' },
      { name: 'value', type: 'ReactNode', required: false, description: 'stat/metric 값 영역을 전달한다.' },
      { name: 'children', type: 'ReactNode', required: false, description: 'SectionPanel, ActionBar, HoverCard의 내부 콘텐츠를 구성한다.' },
    ],
    variants: [
      { name: 'block type', values: ['StatCard', 'MetricCard', 'AssignmentRow', 'PreviewCard', 'HoverCard', 'SectionPanel', 'ActionBar'], description: '같은 dense workspace 안에서도 용도별로 block을 나눈다.' },
    ],
    related: ['data-grid', 'charts', 'settings-shell'],
    notes: ['이 묶음은 공용 표현 계층이다. 프로젝트 의미가 붙는 action flow는 앱에 남긴다.'],
    dos: ['dense screen도 공용 block 조합으로 시작한다.'],
    donts: ['feature마다 새로운 card shell을 하나씩 만들지 않는다.'],
  }),
  entry({
    id: 'alert',
    section: 'components',
    group: 'feedback',
    title: 'Alert',
    summary: 'success, warning, info 같은 semantic feedback banner다.',
    whenToUse: '사용자에게 상태, 결과, 주의사항을 inline으로 알릴 때 사용한다.',
    whenNotToUse: '단순 장식 배너나 비구조적 문단을 alert처럼 쓰지 않는다.',
    importPath: "import { Alert } from '@ingradient/ui/components'",
    examples: [{ title: 'Semantic alerts', description: 'Info, success, and warning feedback banners.', component: AlertDemo }],
    states: ['info', 'success', 'warning'],
    props: [
      { name: 'tone', type: 'semantic tone', required: false, description: 'alert 색상 의미를 정한다.' },
      { name: 'title', type: 'ReactNode', required: false, description: '핵심 메시지 제목을 표시한다.' },
      { name: 'children', type: 'ReactNode', required: true, description: '본문 메시지다.' },
    ],
    variants: [{ name: 'tone', values: ['info', 'success', 'warning', 'danger'], description: '피드백 의미에 따라 tone을 고른다.' }],
    related: ['empty-loading', 'dialog'],
    notes: ['alert는 메시지 layer다. modal confirmation이나 toast 대체용이 아니다.'],
    dos: ['상태 의미가 명확할 때 semantic tone을 사용한다.'],
    donts: ['긴 사용 가이드를 alert 안에 모두 넣지 않는다.'],
  }),
  entry({
    id: 'empty-loading',
    section: 'components',
    group: 'feedback',
    title: 'Empty & Loading',
    summary: '빈 상태, loading 상태, error fallback을 위한 기본 피드백 surface다.',
    whenToUse: '데이터가 없거나 아직 로딩되지 않았을 때 공백을 설명 가능한 surface로 바꿀 때 사용한다.',
    whenNotToUse: '정상적인 목록/그리드 콘텐츠를 전부 이 상태 컴포넌트로 대체하지 않는다.',
    importPath: "import { EmptyState, LoadingState } from '@ingradient/ui/components'",
    examples: [{ title: 'Empty and loading states', description: 'Fallback surfaces for loading, empty, and error moments.', component: StateDemo }],
    states: ['empty', 'loading', 'error-like'],
    props: [
      { name: 'title', type: 'ReactNode', required: false, description: '상태 제목을 표시한다.' },
      { name: 'description', type: 'ReactNode', required: false, description: '보조 설명을 표시한다.' },
      { name: 'actions', type: 'ReactNode', required: false, description: '다시 시도 또는 생성 action을 넣는다.' },
    ],
    variants: [{ name: 'state type', values: ['empty', 'loading'], description: '상황에 따라 적절한 fallback block을 선택한다.' }],
    related: ['alert', 'data-grid'],
    notes: ['상태 fallback은 문서화된 메시지와 다음 action을 같이 제공해야 효과가 좋다.'],
    dos: ['empty state에는 왜 비어 있는지와 다음 행동을 같이 넣는다.'],
    donts: ['로딩 화면을 스피너 하나로 끝내지 않는다.'],
  }),
  entry({
    id: 'card',
    section: 'components',
    group: 'surfaces',
    title: 'Card',
    summary: '강조된 정보 묶음이나 탭이 들어간 module을 표현하는 surface component다.',
    whenToUse: 'overview block, onboarding card, highlighted workspace summary가 필요할 때 사용한다.',
    whenNotToUse: '단순 panel과 같은 역할을 하는데 card를 남발하지 않는다.',
    importPath: "import { Card, Tabs } from '@ingradient/ui/components'",
    examples: [{ title: 'Card with animated tabs', description: 'Card module with tab highlight movement.', component: CardDemo }],
    states: ['default', 'tabbed'],
    props: [
      { name: 'children', type: 'ReactNode', required: true, description: '카드 콘텐츠를 구성한다.' },
      { name: 'style / className', type: 'standard props', required: false, description: 'layout과 size만 최소 범위에서 조정한다.' },
    ],
    variants: [{ name: 'usage mode', values: ['simple content', 'tabbed content'], description: '정적 카드 또는 탭 모듈로 사용한다.' }],
    related: ['accordion', 'navigation', 'workspace-blocks'],
    notes: ['탭 애니메이션은 공용 Tabs가 담당하므로 카드 안에서 직접 구현하지 않는다.'],
    dos: ['강조된 묶음에만 card elevation을 쓴다.'],
    donts: ['모든 panel을 card로 올려서 정보 위계를 흐리지 않는다.'],
  }),
  entry({
    id: 'accordion',
    section: 'components',
    group: 'surfaces',
    title: 'Accordion',
    summary: 'progressive disclosure가 필요한 설정, FAQ, dense docs section에 쓰는 surface다.',
    whenToUse: '한 번에 다 보여주면 길어지는 보조 정보를 접고 펼칠 때 사용한다.',
    whenNotToUse: '핵심 action과 필수 폼 내용을 accordion 안에 숨기지 않는다.',
    importPath: "import { Accordion } from '@ingradient/ui/components'",
    examples: [{ title: 'Progressive disclosure', description: 'Collapsed and open accordion surfaces.', component: AccordionDemo }],
    states: ['collapsed', 'open'],
    props: [
      { name: 'title', type: 'ReactNode', required: true, description: 'accordion header 제목이다.' },
      { name: 'children', type: 'ReactNode', required: true, description: '펼쳤을 때 보이는 내용이다.' },
      { name: 'defaultOpen', type: 'boolean', required: false, description: '초기 open 상태를 지정한다.' },
    ],
    variants: [{ name: 'state', values: ['collapsed', 'open'], description: '문맥에 따라 기본 open 상태를 다르게 잡을 수 있다.' }],
    related: ['card', 'form-section'],
    notes: ['accordion은 보조 정보에 적합하고, primary workflow에는 과하게 숨김을 만들 수 있다.'],
    dos: ['설정/문서성 보조 정보를 단계적으로 노출한다.'],
    donts: ['중요한 오류나 필수 필드를 접혀 있는 상태로 숨기지 않는다.'],
  }),
  entry({
    id: 'navigation',
    section: 'components',
    group: 'navigation',
    title: 'Navigation',
    summary: 'Breadcrumbs, Pagination, Stepper, animated Tabs를 포함한 공용 navigation set이다.',
    whenToUse: '위치 표시, 단계 진행, 페이지 이동, 상위 탭 전환이 필요할 때 사용한다.',
    whenNotToUse: 'product-specific sidebar information architecture 자체를 navigation component 안에 고정하지 않는다.',
    importPath: "import { Breadcrumbs, Pagination, Stepper, Tabs } from '@ingradient/ui/components'",
    examples: [{ title: 'Navigation set', description: 'Breadcrumbs, pagination, stepper, and animated underline tabs.', component: NavigationDemo }],
    states: ['active', 'completed', 'underline-tabs'],
    props: [
      { name: 'items', type: 'array', required: true, description: 'Breadcrumbs, Stepper, Tabs에서 렌더링할 항목 목록이다.' },
      { name: 'value', type: 'string | number', required: false, description: '현재 선택된 탭 또는 페이지 값을 지정한다.' },
      { name: 'onChange', type: '(value) => void', required: false, description: '선택 변경을 처리한다.' },
      { name: 'variant', type: "'pill' | 'underline'", required: false, defaultValue: 'pill', description: 'Tabs 하이라이트 방식을 고른다.' },
    ],
    variants: [
      { name: 'Tabs variant', values: ['pill', 'underline'], description: 'compact segmented control 또는 top-level underline tab으로 표현한다.' },
    ],
    related: ['app-shell', 'sidebar-shell', 'toolbar'],
    notes: ['상위 탭 하이라이트 이동 애니메이션은 Tabs에서 표준 동작으로 보장한다.'],
    dos: ['같은 탭군에는 같은 variant를 유지한다.'],
    donts: ['화면마다 다른 underline animation을 따로 구현하지 않는다.'],
  }),
  entry({
    id: 'icon-gallery',
    section: 'components',
    group: 'icons',
    title: 'Icons',
    summary: 'navigation, status, media, workspace action에 쓰는 curated icon registry다.',
    whenToUse: '새 icon이 필요할 때 먼저 registry 안에 있는 기존 icon으로 해결 가능한지 확인할 때 사용한다.',
    whenNotToUse: 'feature마다 새로운 icon 스타일 체계를 독자적으로 만들지 않는다.',
    importPath: "import { IconGallery, icons } from '@ingradient/ui/components'",
    examples: [{ title: 'Curated icon registry', description: 'Available product-safe icon names and preview grid.', component: IconsDemo }],
    states: ['default'],
    props: [
      { name: 'name', type: 'icon key', required: true, description: 'registry 안의 icon 이름을 지정한다.' },
      { name: 'size', type: 'number', required: false, description: '아이콘 크기를 조절한다.' },
      { name: 'strokeWidth', type: 'number', required: false, description: '선 굵기를 조절한다.' },
    ],
    variants: [{ name: 'usage mode', values: ['inline icon', 'icon button', 'gallery preview'], description: '텍스트 보조, 버튼 액션, registry 문서화 등 다양한 맥락에 쓴다.' }],
    related: ['brand', 'navigation', 'button'],
    notes: ['icon registry는 공용 action language를 유지하기 위한 장치다.'],
    dos: ['새 화면도 우선 registry icon으로 표현한다.'],
    donts: ['같은 의미의 icon을 여러 형태로 중복 도입하지 않는다.'],
  }),
  entry({
    id: 'dialog',
    section: 'components',
    group: 'overlays',
    title: 'Dialog',
    summary: '확인, 폼, destructive action에 쓰는 재사용 가능한 modal shell이다.',
    whenToUse: '화면 위에 집중된 decision 또는 short form flow가 필요할 때 사용한다.',
    whenNotToUse: '긴 multi-pane workflow를 좁은 dialog 안에 욱여넣지 않는다.',
    importPath: "import { DialogShell, ConfirmDialog } from '@ingradient/ui/components'",
    examples: [{ title: 'Dialog shell and confirm flow', description: 'Shared modal shell for forms and confirm actions.', component: DialogDemo }],
    states: ['closed', 'open', 'confirm'],
    props: [
      { name: 'title', type: 'ReactNode', required: true, description: 'dialog header title이다.' },
      { name: 'description', type: 'ReactNode', required: false, description: 'header 아래 설명을 넣는다.' },
      { name: 'children', type: 'ReactNode', required: false, description: 'dialog 본문 콘텐츠다.' },
      { name: 'actions', type: 'ReactNode', required: false, description: 'footer action row를 직접 조합한다.' },
      { name: 'onClose', type: '() => void', required: false, description: 'backdrop 및 close button 동작을 처리한다.' },
      { name: 'width', type: 'string | number', required: false, defaultValue: 'min(720px, 100%)', description: 'dialog 폭을 지정한다.' },
    ],
    variants: [
      { name: 'dialog type', values: ['DialogShell', 'ConfirmDialog'], description: '일반 shell 또는 opinionated confirm flow를 고른다.' },
    ],
    related: ['overlay-blocks', 'drawer', 'alert'],
    notes: ['공용 dialog shell로 감싸고, feature-specific body만 주입하는 것이 기본 패턴이다.'],
    dos: ['짧은 설명과 명확한 action을 함께 둔다.'],
    donts: ['화면 전체 settings shell을 modal 하나로 대체하지 않는다.'],
  }),
  entry({
    id: 'overlay-blocks',
    section: 'components',
    group: 'overlays',
    title: 'Dialogs & Menus',
    summary: 'menu popover, hover card, section panel, compact modal primitives 같은 overlay building block 묶음이다.',
    whenToUse: 'dialog 전체를 만들기 전에 작은 overlay block 조합으로 해결 가능한지 볼 때 사용한다.',
    whenNotToUse: '복잡한 app-specific overlay workflow를 core block 안에 고정하지 않는다.',
    importPath: "import { MenuPopover, HoverCard, SectionPanel, ActionBar, ModalBackdrop, CompactModalCard } from '@ingradient/ui/components'",
    examples: [{ title: 'Overlay building blocks', description: 'Menu popover, hover card, section panel, and modal primitives.', component: OverlayBlocksDemo }],
    states: ['menu', 'dialog', 'hover'],
    props: [
      { name: 'trigger', type: 'ReactNode', required: false, description: 'popover류의 trigger 요소다.' },
      { name: 'children', type: 'ReactNode', required: true, description: 'overlay 본문 콘텐츠다.' },
      { name: 'open', type: 'boolean', required: false, description: 'controlled open 상태를 전달한다.' },
    ],
    variants: [{ name: 'block type', values: ['menu', 'hover card', 'section panel', 'compact modal'], description: 'overlay 목적에 따라 더 작은 building block을 고른다.' }],
    related: ['dialog', 'tooltip', 'drawer'],
    notes: ['작은 overlay는 full dialog보다 부담이 적다. 다만 중요 결정은 dialog가 더 명확하다.'],
    dos: ['작은 contextual action은 menu/hover card부터 고려한다.'],
    donts: ['간단한 contextual action을 full-screen modal로 과하게 감싸지 않는다.'],
  }),
  entry({
    id: 'drawer',
    section: 'components',
    group: 'overlays',
    title: 'Drawer',
    summary: '보조 설정, filter panel, mobile navigation context에 적합한 side sheet다.',
    whenToUse: '보조 정보나 secondary workflow를 화면 옆에서 보여줄 때 사용한다.',
    whenNotToUse: '짧은 confirm action이나 단일 decision은 dialog가 더 적합하다.',
    importPath: "import { Drawer } from '@ingradient/ui/components'",
    examples: [{ title: 'Drawer surface', description: 'Side sheet for settings and supporting context.', component: DrawerDemo }],
    states: ['closed', 'open'],
    props: [
      { name: 'open', type: 'boolean', required: true, description: 'drawer 가시 상태를 제어한다.' },
      { name: 'onClose', type: '() => void', required: false, description: '닫기 동작을 처리한다.' },
      { name: 'children', type: 'ReactNode', required: true, description: 'drawer 내부 콘텐츠다.' },
    ],
    variants: [{ name: 'usage mode', values: ['filters', 'settings', 'supporting context'], description: 'secondary workflow를 옆에서 보조하는 데 쓴다.' }],
    related: ['dialog', 'split-layout'],
    notes: ['drawer는 supporting context에 강하고, primary action flow를 대신하는 패턴은 아니다.'],
    dos: ['desktop inspector와 mobile fallback 모두에 활용한다.'],
    donts: ['필수 initial setup을 drawer 뒤로 숨기지 않는다.'],
  }),
  entry({
    id: 'tooltip',
    section: 'components',
    group: 'overlays',
    title: 'Tooltip',
    summary: 'dense UI에서 짧은 설명과 context hint를 제공하는 compact overlay다.',
    whenToUse: '아이콘 버튼, 짧은 label, 잘린 텍스트에 짧은 설명이 필요할 때 사용한다.',
    whenNotToUse: '긴 문단, action-rich content, critical warning을 tooltip에 넣지 않는다.',
    importPath: "import { TooltipBubble } from '@ingradient/ui/components'",
    examples: [{ title: 'Compact helper overlay', description: 'Short explanatory tooltip surface.', component: TooltipDemo }],
    states: ['default', 'hover'],
    props: [
      { name: 'children', type: 'ReactNode', required: true, description: 'tooltip 콘텐츠다.' },
      { name: 'position', type: 'placement', required: false, description: '표시 위치를 조정한다.' },
    ],
    variants: [{ name: 'placement', values: ['top', 'right', 'bottom', 'left'], description: 'trigger 주변 배치 방향을 조정한다.' }],
    related: ['overlay-blocks', 'alert'],
    notes: ['tooltip은 짧고 즉시성 있는 설명에만 적합하다.'],
    dos: ['icon-only control에는 tooltip을 함께 제공한다.'],
    donts: ['핵심 정보나 필수 validation을 tooltip에만 넣지 않는다.'],
  }),
]
