import {
  HooksDemo, SearchFieldDemo, NumberFieldDemo, MentionTextareaDemo,
  SelectionActionBarDemo, EmptyStateDemo, CommentThreadDemo,
  ColorSwatchTagListDemo, ImageViewerDemo, InteractionDemo, LayoutDemo,
} from '../newShowcaseDemos'
import type { DocEntry } from './types'

function entry(input: Omit<DocEntry, 'status'> & { status?: DocEntry['status'] }): DocEntry {
  return { status: 'draft', ...input }
}

export const newComponentDocs: DocEntry[] = [
  // ── Hooks ──────────────────────────────────────────────────────────
  entry({
    id: 'hooks',
    section: 'components',
    group: 'hooks',
    title: 'Hooks',
    summary: 'useZoomPan, useSelection, useClipboard, useUndoRedo, useDrawingCanvas',
    whenToUse: '이미지 줌/팬, 멀티 셀렉트, 클립보드 복사, undo/redo, 캔버스 드로잉이 필요할 때',
    importPath: "import { useZoomPan, useSelection, useClipboard, useUndoRedo, useDrawingCanvas } from '@ingradient/ui/components'",
    examples: [{ title: 'All hooks', description: '각 hook의 기본 동작', component: HooksDemo }],
    states: [],
    props: [
      { name: 'useZoomPan options', type: '{ minZoom?, maxZoom?, zoomStep? }', required: false, description: '줌 범위와 단계' },
      { name: 'useSelection items', type: '{ id: string }[]', required: true, description: '셀렉트 대상 아이템 배열' },
      { name: 'useClipboard options', type: '{ resetDelay? }', required: false, description: 'copied 상태 리셋 지연 (ms)' },
      { name: 'useUndoRedo options', type: '{ initialState, maxHistory? }', required: true, description: '초기 상태와 히스토리 최대 크기' },
    ],
    variants: [],
    related: ['image-viewer', 'drawing-layer'],
    notes: ['hooks는 React만 의존. tokens/components를 import하지 않는다.'],
    dos: ['ImageViewer와 DrawingLayer를 조합할 때 useZoomPan + useDrawingCanvas를 함께 사용한다.', 'useDrawingCanvas는 드래그 중 document 레벨 이벤트를 사용하므로 컨테이너 밖에서도 동작한다.'],
    donts: ['useDrawingCanvas를 DrawingLayer 없이 단독으로 사용하지 않는다.'],
  }),

  // ── Inputs ─────────────────────────────────────────────────────────
  entry({
    id: 'search-field',
    section: 'components',
    group: 'inputs',
    title: 'SearchField',
    summary: '돋보기 아이콘 + clear 버튼이 포함된 검색 입력',
    whenToUse: '목록, 테이블, 사이드바에서 필터링 검색이 필요할 때',
    importPath: "import { SearchField } from '@ingradient/ui/components'",
    examples: [{ title: 'Default + Small', description: 'md/sm 사이즈와 clear 버튼', component: SearchFieldDemo }],
    states: ['empty', 'filled', 'sm size'],
    props: [
      { name: 'value', type: 'string', required: true, description: '검색어' },
      { name: 'onClear', type: '() => void', required: false, description: 'clear 버튼 콜백' },
      { name: 'size', type: "'sm' | 'md'", required: false, defaultValue: 'md', description: '크기' },
    ],
    variants: [{ name: 'size', values: ['sm', 'md'], description: '검색 바 높이' }],
    related: ['text-field', 'filter-bar-layout'],
    notes: ['onClear가 없으면 clear 버튼이 숨겨진다.'],
    dos: ['목록 필터링에 사용한다.'],
    donts: ['일반 텍스트 입력 대신 사용하지 않는다.'],
  }),

  entry({
    id: 'number-field',
    section: 'components',
    group: 'inputs',
    title: 'NumberField',
    summary: 'Draft string 유지, blur/Enter commit, ArrowUp/Down 지원 숫자 입력',
    whenToUse: '범위가 있는 숫자 값을 정밀하게 입력할 때',
    importPath: "import { NumberField } from '@ingradient/ui/components'",
    examples: [{ title: 'Basic', description: 'min/max + ArrowUp/Down', component: NumberFieldDemo }],
    states: ['normal', 'clamped', 'formatted'],
    props: [
      { name: 'value', type: 'number', required: true, description: '현재 값' },
      { name: 'onChange', type: '(v: number) => void', required: true, description: '값 변경' },
      { name: 'min / max', type: 'number', required: false, description: '범위' },
      { name: 'format', type: '(v: number) => string', required: false, description: '표시 형식' },
    ],
    variants: [],
    related: ['text-field', 'form-group'],
    notes: ['잘못된 입력은 blur 시 이전 값으로 복원된다.'],
    dos: ['min/max를 명시해서 범위 제한을 건다.'],
    donts: ['자유 텍스트 입력에 사용하지 않는다.'],
  }),

  entry({
    id: 'mention-textarea',
    section: 'components',
    group: 'inputs',
    title: 'MentionTextarea',
    summary: '@트리거 멘션 자동완성 textarea',
    whenToUse: '코멘트 입력에서 사용자 멘션이 필요할 때',
    importPath: "import { MentionTextarea } from '@ingradient/ui/components'",
    examples: [{ title: '@Mention', description: '@를 입력하면 후보 드롭다운', component: MentionTextareaDemo }],
    states: ['idle', 'mention-open', 'mention-selected'],
    props: [
      { name: 'candidates', type: 'MentionCandidate[]', required: true, description: '멘션 후보' },
      { name: 'onSubmit', type: '(text, mentionIds) => void', required: false, description: 'Ctrl+Enter 제출' },
      { name: 'triggerChar', type: 'string', required: false, defaultValue: '@', description: '트리거 문자' },
    ],
    variants: [],
    related: ['comment-thread', 'text-field'],
    notes: ['키보드 ↑↓ + Enter/Tab + Escape 지원.'],
    dos: ['코멘트 시스템에서 사용한다.'],
    donts: ['일반 textarea 대신 사용하지 않는다.'],
  }),

  // ── Feedback ───────────────────────────────────────────────────────
  entry({
    id: 'selection-action-bar',
    section: 'components',
    group: 'feedback',
    title: 'SelectionActionBar',
    summary: '아이템 선택 시 나타나는 액션 바',
    whenToUse: '갤러리, 테이블에서 멀티 셀렉트 후 일괄 작업이 필요할 때',
    importPath: "import { SelectionActionBar } from '@ingradient/ui/components'",
    examples: [{ title: 'With actions', description: '선택 카운트 + 액션 버튼', component: SelectionActionBarDemo }],
    states: ['hidden (count=0)', 'visible'],
    props: [
      { name: 'selectedCount', type: 'number', required: true, description: '선택 수 (0이면 숨김)' },
      { name: 'actions', type: 'ReactNode', required: false, description: '오른쪽 액션 슬롯' },
    ],
    variants: [],
    related: ['hooks', 'image-grid'],
    notes: ['selectedCount === 0 이면 null을 렌더한다.'],
    dos: ['useSelection과 함께 사용한다.'],
    donts: ['항상 보이는 툴바로 사용하지 않는다.'],
  }),

  entry({
    id: 'empty-state',
    section: 'components',
    group: 'feedback',
    title: 'EmptyState',
    summary: '데이터 없음, 검색 결과 없음 등 빈 상태 표시',
    whenToUse: '목록이 비어있거나 필터 결과가 없을 때',
    importPath: "import { EmptyState } from '@ingradient/ui/components'",
    examples: [{ title: 'Variants', description: 'action 포함 / 제목만', component: EmptyStateDemo }],
    states: ['icon + title', 'title + description + action'],
    props: [
      { name: 'icon', type: 'ReactNode', required: false, description: '아이콘' },
      { name: 'title', type: 'string', required: false, description: '제목' },
      { name: 'action', type: '{ label, onClick }', required: false, description: '액션 버튼' },
    ],
    variants: [],
    related: ['spinner', 'skeleton'],
    notes: ['EmptyStateText (deprecated)는 이전 styled div. 새 코드는 EmptyState를 사용한다.'],
    dos: ['아이콘 + 짧은 설명 + 한 가지 액션으로 구성한다.'],
    donts: ['긴 에러 메시지를 넣지 않는다.'],
  }),

  // ── Data Display ───────────────────────────────────────────────────
  entry({
    id: 'image-viewer',
    section: 'components',
    group: 'data-display',
    title: 'ImageViewer',
    summary: '줌/팬 내장 이미지 뷰어. children으로 overlay 주입',
    whenToUse: '이미지를 확대해서 세부 사항을 확인할 때',
    importPath: "import { ImageViewer, ImageViewerToolbar } from '@ingradient/ui/components'",
    examples: [{ title: 'Viewer + Drawing', description: 'ImageViewer + DrawingLayer + ModeSwitcher 조합', component: ImageViewerDemo }],
    states: ['default', 'zoomed', 'panning'],
    props: [
      { name: 'src', type: 'string', required: true, description: '이미지 URL' },
      { name: 'children', type: 'ReactNode', required: false, description: '오버레이 (DrawingLayer 등)' },
      { name: 'zoomOptions', type: 'UseZoomPanOptions', required: false, description: '줌 설정' },
    ],
    variants: [],
    related: ['drawing-layer', 'hooks'],
    notes: ['wheel zoom은 non-passive listener로 등록된다.', 'double-click으로 리셋.'],
    dos: ['DrawingLayer를 children으로 주입한다.'],
    donts: ['zoom 상태를 외부에서 직접 제어하려 하지 않는다.'],
  }),

  entry({
    id: 'drawing-layer',
    section: 'components',
    group: 'data-display',
    title: 'DrawingLayer',
    summary: '이미지 위에 rect/point를 렌더링하는 SVG 오버레이',
    whenToUse: '이미지 위에 사각형/점을 그리거나 표시할 때',
    importPath: "import { DrawingLayer, useDrawingCanvas } from '@ingradient/ui/components'",
    examples: [{ title: 'Drawing', description: 'ImageViewer 데모에서 함께 확인', component: ImageViewerDemo }],
    states: ['empty', 'with objects', 'with selection', 'drawing preview'],
    props: [
      { name: 'objects', type: 'DrawingObject[]', required: true, description: '렌더링할 객체' },
      { name: 'showHandles', type: 'boolean', required: false, defaultValue: 'true', description: '리사이즈 핸들' },
      { name: 'showLabels', type: 'boolean', required: false, defaultValue: 'false', description: '라벨 텍스트' },
      { name: 'containerWidth', type: 'number', required: false, description: '컨테이너 픽셀 너비. 균일 stroke/핸들 렌더링 활성화' },
      { name: 'containerHeight', type: 'number', required: false, description: '컨테이너 픽셀 높이' },
      { name: 'previewColor', type: 'string', required: false, defaultValue: '#4a9eff', description: '드래그 미리보기 bbox 색상' },
    ],
    variants: [],
    related: ['image-viewer', 'hooks'],
    notes: ['좌표는 0~1 정규화 값. SVG viewBox="0 0 1 1".', 'containerWidth/Height를 전달하면 비정방형 이미지에서도 stroke/핸들/라벨이 찌그러지지 않는다.'],
    dos: ['ImageViewer의 children으로 사용한다.', 'class 할당은 앱에서 DrawingObject.color/label로 전달한다.'],
    donts: ['비즈니스 로직(저장, class 연결)을 DrawingLayer에 넣지 않는다.'],
  }),

  entry({
    id: 'comment-thread',
    section: 'components',
    group: 'data-display',
    title: 'CommentThread',
    summary: '코멘트 목록 + 입력',
    whenToUse: '이미지/문서에 코멘트를 표시하고 입력받을 때',
    importPath: "import { CommentThread, CommentItem, CommentInput } from '@ingradient/ui/components'",
    examples: [{ title: 'Thread + Input', description: '코멘트 목록과 입력', component: CommentThreadDemo }],
    states: ['empty', 'with comments', 'with input'],
    props: [
      { name: 'author', type: 'string', required: true, description: 'CommentItem: 작성자' },
      { name: 'body', type: 'string', required: true, description: 'CommentItem: 본문' },
      { name: 'onSubmit', type: '() => void', required: false, description: 'CommentInput: Ctrl+Enter 제출' },
    ],
    variants: [],
    related: ['mention-textarea'],
    notes: ['CRUD 로직은 앱에서 처리. UI 렌더링만 담당.'],
    dos: ['CommentInput의 onSubmit에서 API 호출을 처리한다.'],
    donts: ['CommentThread 안에 비즈니스 로직을 넣지 않는다.'],
  }),

  entry({
    id: 'tag-list',
    section: 'components',
    group: 'data-display',
    title: 'TagList & TagListSearch',
    summary: '색상 태그 목록 + 검색 드롭다운',
    whenToUse: '라벨/카테고리 목록에서 색상 태그를 선택할 때',
    importPath: "import { TagList, TagListSearch, ColorSwatch } from '@ingradient/ui/components'",
    examples: [{ title: 'ColorSwatch + TagList + Search', description: '색상 스와치, 태그 목록, 검색 드롭다운', component: ColorSwatchTagListDemo }],
    states: ['list only', 'with search open', 'search empty'],
    props: [
      { name: 'items', type: 'TagItemData[]', required: true, description: 'TagList: 태그 목록' },
      { name: 'candidates', type: 'TagSearchCandidate[]', required: true, description: 'TagListSearch: 검색 후보' },
    ],
    variants: [],
    related: ['color-swatch', 'search-field'],
    notes: ['TagListSearch는 click-outside로 드롭다운이 닫힌다.'],
    dos: ['TagList로 연결된 항목을 보여주고 TagListSearch로 새 항목을 추가한다.'],
    donts: ['CRUD API를 컴포넌트 안에 넣지 않는다.'],
  }),

  // ── Date Picker ──────────────────────────────────────────────────
  entry({
    id: 'date-picker',
    section: 'components',
    group: 'inputs',
    title: 'DatePickerField',
    summary: '날짜를 선택하는 커스텀 달력 컴포넌트. 네이티브 date input 대신 사용한다.',
    whenToUse: '날짜 입력이 필요할 때. From/To 범위, 만료일, 유효기간 등.',
    importPath: "import { DatePickerField } from '@ingradient/ui/components'",
    examples: [],
    states: [],
    props: [
      { name: 'value', type: 'string', required: true, description: '선택된 날짜 값' },
      { name: 'onChange', type: '(value: string) => void', required: true, description: '날짜 변경 콜백' },
      { name: 'placeholder', type: 'string', required: false, defaultValue: 'Select date', description: '플레이스홀더 텍스트' },
      { name: 'disabled', type: 'boolean', required: false, description: '비활성 상태' },
    ],
    variants: [],
    related: ['text-field', 'number-field'],
    notes: ['네이티브 date input 대신 커스텀 달력 UI를 사용한다.'],
    dos: ['From/To 범위, 만료일, 유효기간 등 날짜 입력에 사용한다.'],
    donts: ['시간 선택이 필요한 경우 단독으로 사용하지 않는다.'],
  }),

  // ── Interaction (Phase 8) ──────────────────────────────────────────
  entry({
    id: 'interaction-utils',
    section: 'components',
    group: 'inputs',
    title: 'CopyButton / ModeSwitcher / KeyboardShortcutHint',
    summary: '클립보드 복사 버튼, 모드 전환 그룹, 단축키 힌트',
    whenToUse: '복사 버튼, N개 중 1개 선택, 키보드 단축키 표시가 필요할 때',
    importPath: "import { CopyButton, ModeSwitcher, KeyboardShortcutHint } from '@ingradient/ui/components'",
    examples: [{ title: 'All interactions', description: 'CopyButton + ModeSwitcher + KeyboardShortcutHint', component: InteractionDemo }],
    states: ['default', 'copied', 'active mode'],
    props: [
      { name: 'value (CopyButton)', type: 'string', required: true, description: '복사할 텍스트' },
      { name: 'options (ModeSwitcher)', type: 'ModeSwitcherOption[]', required: true, description: '옵션 배열' },
      { name: 'keys (KeyboardShortcutHint)', type: 'string[]', required: true, description: '키 배열' },
    ],
    variants: [{ name: 'size', values: ['sm', 'md'], description: 'CopyButton, ModeSwitcher, KeyboardShortcutHint 공통' }],
    related: ['hooks', 'drawing-layer'],
    notes: ['CopyButton은 useClipboard를 내장한다.'],
    dos: ['ModeSwitcher는 aria-checked로 접근성을 지원한다.'],
    donts: ['ModeSwitcher를 탭 네비게이션 대신 사용하지 않는다.'],
  }),

  // ── Layout (Phase 9) ──────────────────────────────────────────────
  entry({
    id: 'layout-utils',
    section: 'components',
    group: 'data-display',
    title: 'ChipGroup / FormGroup / FilterBarLayout',
    summary: '칩 그룹, 폼 섹션, 필터 바 레이아웃',
    whenToUse: '오버플로우 칩, 설정 폼, 필터 조합이 필요할 때',
    importPath: "import { ChipGroup, FormGroup, FieldRow, FilterBarLayout } from '@ingradient/ui/components'",
    examples: [{ title: 'All layouts', description: 'ChipGroup + FormGroup + FilterBarLayout', component: LayoutDemo }],
    states: ['chip overflow', 'form section', 'filter bar'],
    props: [
      { name: 'maxVisible (ChipGroup)', type: 'number', required: false, description: '최대 표시 수' },
      { name: 'title (FormGroup)', type: 'string', required: false, description: '섹션 제목' },
      { name: 'label (FieldRow)', type: 'string', required: true, description: '필드 라벨' },
    ],
    variants: [],
    related: ['search-field', 'number-field', 'color-swatch'],
    notes: ['ChipGroup의 maxVisible 초과 시 "+N more" 표시.', 'FieldRow는 grid 레이아웃 (140px + 1fr).'],
    dos: ['FormGroup + FieldRow로 일관된 설정 폼을 만든다.'],
    donts: ['FilterBarLayout 안에 비즈니스 로직을 넣지 않는다.'],
  }),
]
