import {
  AppShellPatternDemo,
  DashboardGridPatternDemo,
  FormSectionPatternDemo,
  ListDetailPatternDemo,
  SettingsShellPatternDemo,
  SidebarShellPatternDemo,
  SplitLayoutPatternDemo,
  ToolbarPatternDemo,
} from '../showcaseRegistry'
import type { DocEntry } from './types'

function pattern(input: Omit<DocEntry, 'status'> & { status?: DocEntry['status'] }): DocEntry {
  return { status: 'ready', ...input }
}

export const patternDocs: DocEntry[] = [
  pattern({
    id: 'app-shell',
    section: 'patterns',
    group: 'shells',
    title: 'App Shell',
    summary: 'top bar, page header, content region을 한 화면 프레임으로 묶는 공용 shell이다.',
    whenToUse: '새로운 product page 또는 workspace를 조립할 때 가장 바깥 프레임으로 사용한다.',
    whenNotToUse: '도메인 고유 navigation flow를 shell 안에 하드코딩하지 않는다.',
    importPath: "import { AppShell, PageHeader, PageHeaderRow, PageTitleBlock, PageTitle, PageSubtitle, PageContent } from '@ingradient/ui/patterns'",
    examples: [{ title: 'Base application frame', description: 'Top bar, page header, and main content composition.', component: AppShellPatternDemo }],
    states: ['desktop', 'mobile'],
    props: [
      { name: 'children', type: 'ReactNode', required: true, description: 'AppShell과 PageContent 안에 실제 페이지 콘텐츠를 넣는다.' },
    ],
    variants: [{ name: 'usage mode', values: ['page shell', 'workspace shell'], description: '페이지형과 작업형 화면 모두의 가장 바깥 레이어로 쓴다.' }],
    chooseThisWhen: ['새 page를 시작할 때 바깥 프레임이 필요할 때', 'header spacing과 content rhythm을 공용화하고 싶을 때'],
    useInsteadWhen: ['작은 modal이나 block 내부 구조만 필요하면 AppShell 대신 FormSection이나 Panel 수준이면 충분하다'],
    related: ['sidebar-shell', 'toolbar', 'navigation'],
    commonComposition: ['AppShell + PageHeader + PageContent + Toolbar + Table', 'AppShell + DashboardGrid + charts'],
    commonMistakes: ['페이지마다 header shell과 outer padding을 따로 만드는 것'],
    notes: ['AppShell은 구조를 제공하고, 실제 business state는 앱이 주입한다.'],
    dos: ['새 페이지는 AppShell 조합부터 시작한다.'],
    donts: ['페이지마다 header와 content outer spacing을 다시 만들지 않는다.'],
  }),
  pattern({
    id: 'sidebar-shell',
    section: 'patterns',
    group: 'shells',
    title: 'Sidebar Shell',
    summary: 'desktop sidebar와 mobile drawer를 같은 공용 구조로 제공하는 navigation shell이다.',
    whenToUse: 'product-wide information architecture나 workspace section navigation을 만들 때 사용한다.',
    whenNotToUse: 'side panel이 단순 inspector라면 sidebar shell 대신 split layout을 쓴다.',
    importPath: "import { AppSidebar, SidebarSection, SidebarFooter, SidebarNav, TopBar, MobileNavDrawer } from '@ingradient/ui/patterns'",
    examples: [{ title: 'Desktop and mobile navigation shell', description: 'Shared sidebar and mobile drawer containers.', component: SidebarShellPatternDemo }],
    states: ['desktop', 'mobile'],
    props: [
      { name: 'children', type: 'ReactNode', required: true, description: 'sidebar 내부 항목과 footer를 구성한다.' },
      { name: '$open', type: 'boolean', required: false, description: 'MobileNavDrawer 열림 상태를 조절한다.' },
    ],
    variants: [{ name: 'shell mode', values: ['desktop sidebar', 'mobile drawer', 'top bar'], description: '디바이스와 정보 구조에 맞게 조합한다.' }],
    related: ['app-shell', 'navigation', 'drawer'],
    notes: ['sidebar 정보 구조 자체는 앱이 소유하고, shell의 시각 구조만 core가 제공한다.'],
    dos: ['desktop과 mobile을 같은 shell family로 유지한다.'],
    donts: ['각 앱이 별도 mobile drawer animation을 다시 구현하지 않는다.'],
  }),
  pattern({
    id: 'toolbar',
    section: 'patterns',
    group: 'page-blocks',
    title: 'Toolbar & Filter Bar',
    summary: 'search, action, filter를 한 줄 또는 래핑 가능한 row로 묶는 page block이다.',
    whenToUse: '목록/그리드 상단에서 검색과 action이 함께 필요한 화면에 사용한다.',
    whenNotToUse: '복잡한 multi-step form 자체를 toolbar 안에 넣지 않는다.',
    importPath: "import { Toolbar, FilterBar } from '@ingradient/ui/patterns'",
    examples: [{ title: 'Search and action rows', description: 'Reusable control rows for filters and page actions.', component: ToolbarPatternDemo }],
    states: ['default', 'wrapped', 'filter'],
    props: [
      { name: 'children', type: 'ReactNode', required: true, description: 'toolbar 안의 검색, 버튼, select 조합을 구성한다.' },
    ],
    variants: [{ name: 'row type', values: ['Toolbar', 'FilterBar'], description: '균등한 action row 또는 검색 중심 filter row로 선택한다.' }],
    related: ['button', 'select', 'data-grid'],
    notes: ['toolbar는 dense control row를 공통화하는 패턴이지, 도메인 action 자체를 캡슐화하는 패턴은 아니다.'],
    dos: ['검색, 선택, primary action을 같은 row 규칙으로 정리한다.'],
    donts: ['toolbar마다 다른 padding과 border shell을 만들지 않는다.'],
  }),
  pattern({
    id: 'split-layout',
    section: 'patterns',
    group: 'layouts',
    title: 'Split Layout',
    summary: 'sidebar, main content, inspector를 조합하는 multi-pane layout 패턴이다.',
    whenToUse: 'dataset browser, catalog, inspector-heavy workspace처럼 여러 열이 필요한 화면에 사용한다.',
    whenNotToUse: '작은 single-column form page를 split layout으로 과하게 복잡하게 만들지 않는다.',
    importPath: "import { SplitLayout, SplitPanelShell, InspectorLayout } from '@ingradient/ui/patterns'",
    examples: [{ title: 'Multi-pane workspace layout', description: 'Sidebar, main content, inspector, and split panels.', component: SplitLayoutPatternDemo }],
    states: ['sidebar', 'inspector', 'two-panel'],
    props: [
      { name: 'sidebar', type: 'ReactNode', required: false, description: '좌측 탐색 또는 supporting rail을 넣는다.' },
      { name: 'content', type: 'ReactNode', required: true, description: '주요 작업 영역을 넣는다.' },
      { name: 'inspector', type: 'ReactNode', required: false, description: '우측 메타/액션 패널을 넣는다.' },
    ],
    variants: [{ name: 'layout mode', values: ['SplitLayout', 'SplitPanelShell', 'InspectorLayout'], description: '열 수와 의미에 맞춰 가장 가까운 패턴을 선택한다.' }],
    chooseThisWhen: ['sidebar, main, inspector 같은 다중 열 구조가 반복될 때', 'browser-like workspace나 settings inspector가 필요할 때'],
    useInsteadWhen: ['단일 column page는 AppShell + PageContent면 충분하다', '명확한 menu + content 구조라면 SettingsShell이 더 읽기 쉽다'],
    related: ['drawer', 'image-grid', 'settings-shell'],
    commonComposition: ['SplitLayout + SidebarNav + ImageGrid + SectionPanel inspector', 'InspectorLayout + Table + detail panel'],
    commonMistakes: ['페이지마다 custom grid template를 새로 정의하는 것'],
    notes: ['split layout은 공간 구조만 제공한다. rail semantics와 inspector business logic는 앱이 소유한다.'],
    dos: ['열 구조가 반복되면 split family로 통일한다.'],
    donts: ['페이지마다 custom grid template를 새로 정의하지 않는다.'],
  }),
  pattern({
    id: 'form-section',
    section: 'patterns',
    group: 'forms',
    title: 'Form Section',
    summary: 'title, helper copy, field group, primary action을 담는 공용 form shell이다.',
    whenToUse: 'settings, create flow, auth, editor에서 논리적으로 묶인 필드 블록이 필요할 때 사용한다.',
    whenNotToUse: '단일 input 하나를 표현하려고 form section 전체를 쓰지 않는다.',
    importPath: "import { FormSection, SectionTitle } from '@ingradient/ui/patterns'",
    examples: [{ title: 'Structured form block', description: 'Title, fields, and action area for a reusable form section.', component: FormSectionPatternDemo }],
    states: ['default', 'loading'],
    props: [
      { name: 'children', type: 'ReactNode', required: true, description: 'field와 action row를 구성한다.' },
    ],
    variants: [{ name: 'usage mode', values: ['create form', 'settings form', 'editor form'], description: 'field grouping을 같은 shell로 통일한다.' }],
    chooseThisWhen: ['논리적으로 같이 저장되는 field 묶음이 있을 때', 'auth, settings, create flow의 폼 블록이 필요할 때'],
    useInsteadWhen: ['field 하나만 놓는 경우는 단일 input + primitive layout이면 충분하다', 'screen 전체 frame은 AppShell이나 SettingsShell이 더 맞다'],
    related: ['text-field', 'checkbox-switch', 'dialog'],
    commonComposition: ['FormSection + TextField + SelectField + Button', 'DialogShell + FormSection'],
    commonMistakes: ['field 하나마다 별도 card를 만드는 것'],
    notes: ['필드 자체보다 form block 구조를 통일하는 것이 목적이다.'],
    dos: ['의미상 같이 수정되는 필드를 한 form section에 묶는다.'],
    donts: ['필드 하나마다 개별 panel을 만들지 않는다.'],
  }),
  pattern({
    id: 'dashboard-grid',
    section: 'patterns',
    group: 'layouts',
    title: 'Dashboard Grid',
    summary: 'metric card와 widget panel을 반응형 grid로 배치하는 dashboard layout이다.',
    whenToUse: 'analytics, status overview, operational summary 화면을 조립할 때 사용한다.',
    whenNotToUse: '고정된 단일-column detail page에 dashboard grid를 억지로 적용하지 않는다.',
    importPath: "import { DashboardGrid, Panel, PanelHeader, PanelTitle, PanelHint } from '@ingradient/ui/patterns'",
    examples: [{ title: 'Responsive widget grid', description: 'Metric and widget layout for dashboards.', component: DashboardGridPatternDemo }],
    states: ['default', 'responsive'],
    props: [
      { name: 'children', type: 'ReactNode', required: true, description: 'widget card와 panel을 배치한다.' },
    ],
    variants: [{ name: 'content mix', values: ['metrics', 'charts', 'lists', 'summaries'], description: '여러 widget을 공통 grid rhythm에 맞춰 섞는다.' }],
    related: ['charts', 'workspace-blocks', 'app-shell'],
    notes: ['widget 내부 시각 규칙은 component layer가 담당하고, DashboardGrid는 배치 리듬을 담당한다.'],
    dos: ['dashboard는 grid 패턴을 먼저 적용하고 block을 채운다.'],
    donts: ['widget마다 다른 outer spacing을 주어 grid rhythm을 깨지 않는다.'],
  }),
  pattern({
    id: 'list-detail',
    section: 'patterns',
    group: 'layouts',
    title: 'List Detail',
    summary: '목록과 상세/에디터를 좌우로 배치하는 common master-detail 패턴이다.',
    whenToUse: '설정 카테고리, 멤버 목록, 템플릿 목록, 에셋 브라우저 상세 편집에 사용한다.',
    whenNotToUse: '목록과 상세가 강하게 연결되지 않은 화면에 억지로 적용하지 않는다.',
    importPath: "import { ListDetailLayout } from '@ingradient/ui/patterns'",
    examples: [{ title: 'Master-detail composition', description: 'Collection on the left and editor/detail on the right.', component: ListDetailPatternDemo }],
    states: ['desktop', 'stacked'],
    props: [
      { name: 'children', type: 'ReactNode', required: true, description: '왼쪽 목록과 오른쪽 상세 패널을 순서대로 넣는다.' },
    ],
    variants: [{ name: 'layout behavior', values: ['two-column desktop', 'stacked mobile'], description: '반응형에서 동일한 정보 관계를 유지한다.' }],
    related: ['settings-shell', 'split-layout', 'data-grid'],
    notes: ['좌우 영역 의미는 앱이 정하지만, 기본 grid ratio는 공용화한다.'],
    dos: ['목록-상세 관계가 명확한 화면에 사용한다.'],
    donts: ['relatedness가 약한 두 영역을 억지로 붙이지 않는다.'],
  }),
  pattern({
    id: 'settings-shell',
    section: 'patterns',
    group: 'layouts',
    title: 'Settings & Inspector Shells',
    summary: 'settings menu + content, main + inspector 같은 운영 화면의 multi-pane shell family다.',
    whenToUse: 'settings, permissions, detail inspector, split workspace를 공통 구조로 만들 때 사용한다.',
    whenNotToUse: '설정 의미가 없는 단순 리스트 화면까지 settings shell로 일반화하지 않는다.',
    importPath: "import { SettingsShell, InspectorLayout, SplitPanelShell } from '@ingradient/ui/patterns'",
    examples: [{ title: 'Settings and inspector family', description: 'SettingsShell, InspectorLayout, and SplitPanelShell examples.', component: SettingsShellPatternDemo }],
    states: ['settings', 'inspector', 'two-panel'],
    props: [
      { name: 'children', type: 'ReactNode', required: true, description: '각 layout family가 요구하는 패널 순서대로 콘텐츠를 넣는다.' },
    ],
    variants: [{ name: 'layout family', values: ['SettingsShell', 'InspectorLayout', 'SplitPanelShell'], description: '좌우 역할과 정보 위계에 맞는 shell을 고른다.' }],
    chooseThisWhen: ['settings menu + content 또는 main + inspector 패턴이 반복될 때', 'permissions, settings, detail inspector를 공통 구조로 만들고 싶을 때'],
    useInsteadWhen: ['더 일반적인 multi-pane browsing이면 SplitLayout이 더 중립적이다', '단순 list/detail은 ListDetailLayout이 더 직접적이다'],
    related: ['split-layout', 'list-detail', 'dialog'],
    commonComposition: ['SettingsShell + SidebarSection + FormSection + Table', 'InspectorLayout + ImageGrid + SectionPanel'],
    commonMistakes: ['설정 의미가 없는 단순 리스트까지 settings shell로 일반화하는 것'],
    notes: ['설정 정보 구조는 앱이 소유하지만, pane shell과 spacing rhythm은 공용화한다.'],
    dos: ['settings와 inspector UI는 같은 shell family를 재사용한다.'],
    donts: ['feature별로 또 다른 multi-pane shell을 만들지 않는다.'],
  }),
]
