import { useState } from 'react'
import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { SettingsModal } from '../../../../stories/pages/edge/0.0.5/settings/build-settings-modal'
import { useSettingsDraft } from '../../../../stories/pages/edge/0.0.5/settings/tabs-moved'
import { AccountRuntime, LanguageRuntime } from '../../../../stories/pages/edge/0.0.5/settings/account-runtime'
import { SystemMonitorRuntime } from '../../../../stories/pages/edge/0.0.5/settings/system-runtime'
import type { SettingsTab, LightingMode } from './types'

// Test source views, not the last built package artifact.
vi.mock('@ingradient/edge-pages', () => import('../index'))
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.useRealTimers() })
function Harness({ initialTab = 'server', lightingMode = 'deflectometry' }: { initialTab?: SettingsTab; lightingMode?: LightingMode }) {
  const draft = useSettingsDraft()
  const [open, setOpen] = useState(true)
  return <><button onClick={() => setOpen(true)}>Reopen</button>{open && <SettingsModal draft={draft} onMockAction={vi.fn()} initialTab={initialTab} lightingMode={lightingMode} onClose={() => setOpen(false)} />}</>
}
const click = (name: string) => fireEvent.click(screen.getByRole('button', { name }))
const tab = (name: string) => fireEvent.click(screen.getByRole('tab', { name }))

describe('settings workflow controllers', () => {
  it('persists edited server and camera drafts across tabs and close/reopen', () => {
    render(<Harness />)
    fireEvent.change(screen.getByLabelText('Base URL'), { target: { value: 'https://mock.example.test' } })
    click('Save')
    expect(screen.getByText(/Mock settings saved/)).toBeVisible()
    tab('Camera')
    fireEvent.change(screen.getByLabelText('cvsCam DLL Path'), { target: { value: 'edited.dll' } })
    click('Apply')
    expect(screen.getByText(/Mock camera apply complete/)).toBeVisible()
    tab('Server')
    expect(screen.getByLabelText('Base URL')).toHaveValue('https://mock.example.test')
    fireEvent.keyDown(document, { key: 'Escape' })
    click('Reopen')
    tab('Camera')
    expect(screen.getByLabelText('cvsCam DLL Path')).toHaveValue('edited.dll')
    click('Reset to Factory Defaults')
    expect(screen.getByLabelText('cvsCam DLL Path')).not.toHaveValue('edited.dll')
  })
  it('validates and applies Force IP to the in-memory camera fixture', () => {
    render(<Harness initialTab="connection" />)
    click('Force IP')
    // Scope repeated queries to the small nested form, not the six-stage settings tree.
    const dialog = within(screen.getByRole('dialog', { name: 'Force IP' }))
    fireEvent.change(dialog.getByLabelText('Static IP'), { target: { value: '999.1.2.3' } })
    fireEvent.click(dialog.getByRole('button', { name: 'Apply' }))
    expect(dialog.getByRole('alert')).toBeVisible()
    fireEvent.change(dialog.getByLabelText('Static IP'), { target: { value: '192.168.1.42' } })
    fireEvent.click(dialog.getByRole('button', { name: 'Apply' }))
    expect(screen.queryByRole('dialog', { name: 'Force IP' })).not.toBeInTheDocument()
    expect(screen.getByText(/Mock force-ip complete/)).toBeVisible()
    expect(screen.getByText(/192.168.1.42/)).toBeVisible()
  })
  it('retains an unapplied Force IP draft when its tab unmounts', () => {
    render(<Harness initialTab="connection" />)
    click('Force IP')
    const dialog = within(screen.getByRole('dialog', { name: 'Force IP' }))
    fireEvent.change(dialog.getByLabelText('Static IP'), { target: { value: '192.168.1.42' } })
    fireEvent.click(dialog.getByRole('button', { name: 'Cancel' }))
    tab('Server'); tab('Connection'); click('Force IP')
    expect(screen.getByLabelText('Static IP')).toHaveValue('192.168.1.42')
  })
  it('filters, clears, refreshes and exports synthetic log entries', () => {
    render(<Harness initialTab="logs" />)
    fireEvent.change(screen.getByRole('searchbox', { name: 'Filter (message, module...)' }), { target: { value: 'capture-agent' } })
    expect(screen.getByText(/capture-agent started/)).toBeVisible()
    expect(screen.queryByText(/cvsCam device opened/)).not.toBeInTheDocument()
    click('Copy all')
    expect(screen.getByText(/1 backend entries/)).toBeVisible()
    click('Clear'); expect(screen.getByText('No logs')).toBeVisible()
    click('Refresh'); expect(screen.getByText(/capture-agent started/)).toBeVisible()
  })
  it('reaches PS branch and preserves channels across tabs', () => {
    render(<Harness initialTab="lighting" lightingMode="photometric-stereo" />)
    click('All on')
    expect(screen.getAllByRole('checkbox').slice(0, 4).every((input) => (input as HTMLInputElement).checked)).toBe(true)
    click('All off'); tab('Server'); tab('Lighting')
    expect(screen.getAllByRole('checkbox').slice(0, 4).every((input) => !(input as HTMLInputElement).checked)).toBe(true)
  })
  it('runs cache cleanup after settings closes and reopens', () => {
    vi.useFakeTimers()
    render(<Harness initialTab="data" />)
    click('Clean Cache'); click('Confirm mock action')
    fireEvent.keyDown(document, { key: 'Escape' })
    act(() => vi.advanceTimersByTime(700))
    click('Reopen')
    expect(screen.getByText(/Mock cache cleanup complete/)).toBeVisible()
  })
  it('cancels, reruns and exports a field test while retaining offscreen progress', () => {
    vi.useFakeTimers()
    render(<Harness initialTab="fieldtest" />)
    click('Run'); click('Cancel')
    expect(screen.getByText('Mock field test cancelled.')).toBeVisible()
    click('Run'); tab('Server')
    for (let i = 0; i < 4; i++) act(() => vi.advanceTimersByTime(300))
    tab('Field Test')
    expect(screen.getByText('Mock field test complete.')).toBeVisible()
    click('Export'); expect(screen.getByText(/Mock field test export prepared/)).toBeVisible()
    click('Reset'); expect(screen.getByText('No results yet.')).toBeVisible()
  })
  it('closes only the nested deactivation code overlay and progresses mock update', () => {
    vi.useFakeTimers()
    render(<Harness initialTab="about" />)
    click('Deactivate License'); click('Confirm mock action')
    expect(screen.getByRole('dialog', { name: 'Deactivation Code' })).toBeVisible()
    fireEvent.keyDown(document, { key: 'Escape' })
    expect(screen.queryByRole('dialog', { name: 'Deactivation Code' })).not.toBeInTheDocument()
    expect(screen.getByRole('dialog', { name: 'System Settings' })).toBeVisible()
    click('Check for Updates'); act(() => vi.advanceTimersByTime(700))
    click('Download'); act(() => vi.advanceTimersByTime(700))
    click('Install & Restart')
    expect(screen.getByText(/Mock update install requested/)).toBeVisible()
  })
  it('changes language and mock account without authentication', () => {
    const action = vi.fn()
    render(<><LanguageRuntime onMockAction={action} /><AccountRuntime onMockAction={action} /></>)
    click('Language'); fireEvent.click(screen.getByRole('option', { name: '한국어' }))
    expect(action).toHaveBeenCalledWith('language-change', 'ko')
    fireEvent.click(screen.getByRole('button', { name: /Account: JOON/ }))
    fireEvent.click(screen.getByRole('menuitem', { name: 'Change Account' }))
    fireEvent.click(within(screen.getByRole('dialog', { name: 'Past Accounts' })).getByRole('button', { name: /Mock Operator/ }))
    expect(screen.getByRole('button', { name: 'Account: Mock Operator' })).toBeVisible()
  })
  it('does not restart cleanup when the action callback changes and cancels pending work on unmount', () => {
    vi.useFakeTimers()
    const schedule = vi.spyOn(globalThis, 'setTimeout')
    const cancel = vi.spyOn(globalThis, 'clearTimeout')
    const firstAction = vi.fn()
    const latestAction = vi.fn()
    const { rerender, unmount } = render(<SystemMonitorRuntime onMockAction={firstAction} />)
    click('Open system monitor'); tab('Cleanup')
    click('Clean selected mock data'); click('Confirm mock action')
    act(() => vi.advanceTimersByTime(350))
    rerender(<SystemMonitorRuntime onMockAction={latestAction} />)
    act(() => vi.advanceTimersByTime(350))
    expect(latestAction).toHaveBeenCalledWith('system-cleanup-complete', { freedBytes: 60 * 1024 ** 2 })
    expect(firstAction).not.toHaveBeenCalledWith('system-cleanup-complete', expect.anything())
    click('Clean selected mock data'); click('Confirm mock action')
    const cleanupTimers = schedule.mock.calls.flatMap(([, delay], index) => delay === 700 ? [schedule.mock.results[index].value] : [])
    expect(cleanupTimers).toHaveLength(2)
    // Assert cancellation of our pending operation, not unrelated jsdom timers.
    unmount()
    expect(cancel).toHaveBeenCalledWith(cleanupTimers[1])
    act(() => vi.advanceTimersByTime(1000))
    expect(latestAction.mock.calls.filter(([name]) => name === 'system-cleanup-complete')).toHaveLength(1)
  })
  it('keeps cleanup running while monitor closes and releases timers on session unmount', () => {
    vi.useFakeTimers()
    const { unmount } = render(<SystemMonitorRuntime />)
    click('Open system monitor'); tab('Cleanup')
    click('Clean selected mock data'); click('Confirm mock action')
    fireEvent.keyDown(document, { key: 'Escape' })
    act(() => vi.advanceTimersByTime(700))
    click('Open system monitor')
    expect(screen.getByText(/Mock cleanup complete:/)).toBeVisible()
    unmount(); expect(vi.getTimerCount()).toBe(0)
  })
})
