import {
  foundationColors,
  radiusScale,
  shadowScale,
  spacingScale,
  typographyScale,
  zIndexScale,
} from '../foundations'
import { ingradientTheme } from '../semantic/theme'

export const tokenCssVariables = {
  '--ig-color-bg-canvas': ingradientTheme.colors.bgCanvas,
  '--ig-color-bg-canvas-alt': ingradientTheme.colors.bgCanvasAlt,
  '--ig-color-bg-radial-a': ingradientTheme.colors.bgRadialA,
  '--ig-color-bg-radial-b': ingradientTheme.colors.bgRadialB,
  '--ig-color-surface-header': ingradientTheme.colors.surfaceHeader,
  '--ig-color-surface-panel': ingradientTheme.colors.surfacePanel,
  '--ig-color-surface-raised': ingradientTheme.colors.surfaceRaised,
  '--ig-color-surface-muted': ingradientTheme.colors.surfaceMuted,
  '--ig-color-surface-interactive': ingradientTheme.colors.surfaceInteractive,
  '--ig-color-surface-active': ingradientTheme.colors.surfaceActive,
  '--ig-color-border-subtle': ingradientTheme.colors.borderSubtle,
  '--ig-color-border-strong': ingradientTheme.colors.borderStrong,
  '--ig-color-text-primary': ingradientTheme.colors.textPrimary,
  '--ig-color-text-secondary': ingradientTheme.colors.textSecondary,
  '--ig-color-text-muted': ingradientTheme.colors.textMuted,
  '--ig-color-text-soft': ingradientTheme.colors.textSoft,
  '--ig-color-accent': ingradientTheme.colors.accent,
  '--ig-color-accent-strong': ingradientTheme.colors.accentStrong,
  '--ig-color-accent-soft': ingradientTheme.colors.accentSoft,
  '--ig-color-success': ingradientTheme.colors.success,
  '--ig-color-warning': ingradientTheme.colors.warning,
  '--ig-color-danger': ingradientTheme.colors.danger,
  '--ig-color-surface-card-a': 'rgba(18, 21, 28, 0.96)',
  '--ig-color-surface-card-b': 'rgba(10, 14, 20, 0.96)',
  '--ig-color-surface-interactive-hover': foundationColors.white07,
  '--ig-color-surface-focus': 'rgba(16, 22, 32, 0.98)',
  '--ig-color-accent-ring': 'rgba(91, 144, 255, 0.7)',
  '--ig-color-accent-border-strong': foundationColors.blueTint38,
  '--ig-color-accent-soft-surface': foundationColors.blueTint12,
  '--ig-color-accent-soft-surface-hover': foundationColors.blueTint18,
  '--ig-color-inset-highlight': 'rgba(255, 255, 255, 0.04)',
  '--ig-radius-sm': ingradientTheme.radius.sm,
  '--ig-radius-md': ingradientTheme.radius.md,
  '--ig-radius-lg': ingradientTheme.radius.lg,
  '--ig-radius-xl': ingradientTheme.radius.xl,
  '--ig-radius-pill': ingradientTheme.radius.pill,
  '--ig-radius-xs': radiusScale.xs,
  '--ig-radius-sm-alt': radiusScale.sm,
  '--ig-radius-lg-alt': radiusScale.lg,
  '--ig-radius-2xl': radiusScale['2xl'],
  '--ig-radius-3xl': radiusScale['3xl'],
  '--ig-radius-4xl': radiusScale['4xl'],
  '--ig-shadow-panel': ingradientTheme.shadows.panel,
  '--ig-shadow-floating': ingradientTheme.shadows.floating,
  '--ig-shadow-popover': shadowScale.popover,
  '--ig-shadow-hover-lift': shadowScale.hoverLift,
  '--ig-shadow-focus-ring': shadowScale.focusRing,
  '--ig-font-sans': ingradientTheme.typography.fontSans,
  '--ig-font-mono': ingradientTheme.typography.fontMono,
  '--ig-font-size-2xs': typographyScale.size2xs,
  '--ig-font-size-xs': typographyScale.sizeXs,
  '--ig-font-size-sm': typographyScale.sizeSm,
  '--ig-font-size-md': typographyScale.sizeMd,
  '--ig-font-size-lg': typographyScale.sizeLg,
  '--ig-font-size-xl': typographyScale.sizeXl,
  '--ig-font-size-2xl': typographyScale.size2xl,
  '--ig-font-size-3xl': typographyScale.size3xl,
  '--ig-font-size-4xl': typographyScale.size4xl,
  '--ig-font-size-5xl': typographyScale.size5xl,
  '--ig-space-0': spacingScale[0],
  '--ig-space-1': spacingScale[1],
  '--ig-space-2': spacingScale[2],
  '--ig-space-3': spacingScale[3],
  '--ig-space-4': spacingScale[4],
  '--ig-space-5': spacingScale[5],
  '--ig-space-6': spacingScale[6],
  '--ig-space-7': spacingScale[7],
  '--ig-space-8': spacingScale[8],
  '--ig-space-9': spacingScale[9],
  '--ig-space-10': spacingScale[10],
  '--ig-space-11': spacingScale[11],
  '--ig-space-12': spacingScale[12],
  '--ig-space-13': spacingScale[13],
  '--ig-z-popover': String(zIndexScale.popover),
  '--ig-z-drawer': String(zIndexScale.drawer),
  '--ig-z-modal': String(zIndexScale.modal),
  '--ig-scrollbar-thumb': 'rgba(148, 163, 184, 0.22)',
  '--ig-scrollbar-thumb-hover': 'rgba(148, 163, 184, 0.34)',
  '--ig-scrollbar-thumb-active': 'rgba(148, 163, 184, 0.42)',
  '--ig-color-status-running-bg': foundationColors.greenTint18,
  '--ig-color-status-running-text': foundationColors.textSuccess,
  '--ig-color-status-completed-bg': foundationColors.cyanTint18,
  '--ig-color-status-completed-text': foundationColors.textCyan,
  '--ig-color-status-queued-bg': foundationColors.blueTint18,
  '--ig-color-status-queued-text': foundationColors.textBlue,
  '--ig-color-status-draft-bg': foundationColors.amberTint20,
  '--ig-color-status-draft-text': foundationColors.textWarning,
  '--ig-color-status-failed-bg': foundationColors.redTint18,
  '--ig-color-status-failed-text': foundationColors.textDanger,
  '--ig-color-status-stopped-bg': 'rgba(148, 163, 184, 0.16)',
  '--ig-color-status-stopped-text': foundationColors.textSlateSoft,
  '--ig-color-status-interrupted-bg': foundationColors.amberTint18,
  '--ig-color-status-interrupted-text': foundationColors.textOrange,
  '--ig-color-status-warning-bg': foundationColors.amberTint18,
  '--ig-color-status-warning-text': foundationColors.textOrange,
  '--ig-color-status-idle-bg': 'rgba(67, 76, 94, 0.22)',
  '--ig-color-status-idle-text': foundationColors.textSlate,
  '--ig-color-alert-info-bg': foundationColors.blueTint12,
  '--ig-color-alert-info-border': 'rgba(77, 136, 255, 0.26)',
  '--ig-color-alert-info-text': foundationColors.textInfo,
  '--ig-color-alert-success-bg': foundationColors.greenTint12,
  '--ig-color-alert-success-border': 'rgba(43, 181, 114, 0.26)',
  '--ig-color-alert-success-text': foundationColors.textSuccessSoft,
  '--ig-color-alert-warning-bg': 'rgba(251, 146, 60, 0.12)',
  '--ig-color-alert-warning-border': 'rgba(251, 146, 60, 0.26)',
  '--ig-color-alert-warning-text': foundationColors.textWarningSoft,
  '--ig-color-alert-danger-bg': foundationColors.redTint12,
  '--ig-color-alert-danger-border': 'rgba(239, 68, 68, 0.26)',
  '--ig-color-alert-danger-text': foundationColors.textDangerSoft,
  '--ig-color-chart-1': foundationColors.blue500,
  '--ig-color-chart-2': foundationColors.green500,
  '--ig-color-chart-3': foundationColors.amber500,
  '--ig-color-chart-4': foundationColors.red300,
  '--ig-color-chart-5': foundationColors.blue300,
  '--ig-color-chart-6': foundationColors.violet300,
  '--ig-color-chart-grid': 'rgba(255, 255, 255, 0.08)',
  '--ig-color-badge-neutral': foundationColors.white08,
  '--ig-color-badge-accent': foundationColors.blueTint18,
  '--ig-color-badge-success': foundationColors.greenTint18,
  '--ig-color-badge-warning': foundationColors.amberTint18,
  '--ig-color-badge-danger': foundationColors.redTint18,
  '--ig-color-progress-track': foundationColors.white08,
  '--ig-color-skeleton-start': foundationColors.white06,
  '--ig-color-skeleton-mid': foundationColors.white12,
  '--ig-color-image-card-hover-border': foundationColors.blueTint28,
  '--ig-color-image-card-selected-border': foundationColors.blueTint42,
  '--ig-color-image-card-selected-ring': foundationColors.blueTint18,
  '--ig-color-image-card-gradient-a': foundationColors.blueTint14,
  '--ig-color-image-card-gradient-b': foundationColors.greenTint12,
  '--ig-color-avatar-bg': foundationColors.blueTint18,
  '--ig-color-dropdown-trigger-shadow':
    'inset 0 1px 0 var(--ig-color-inset-highlight), 0 10px 24px rgba(0, 0, 0, 0.12)',
  '--ig-color-dropdown-open-shadow':
    '0 0 0 3px rgba(77, 136, 255, 0.16), 0 18px 36px rgba(0, 0, 0, 0.18)',
  '--ig-color-dropdown-chevron-bg': foundationColors.white04,
  '--ig-color-dropdown-chevron-border': foundationColors.borderMuted,
  '--ig-color-dropdown-menu-a': 'rgba(18, 24, 34, 0.98)',
  '--ig-color-dropdown-menu-b': 'rgba(10, 14, 20, 0.98)',
  '--ig-color-dropdown-option-hover': foundationColors.white06,
  '--ig-color-toggle-on-bg': 'rgba(77, 136, 255, 0.4)',
  '--ig-color-toggle-on-border': 'rgba(77, 136, 255, 0.55)',
  '--ig-color-toggle-off-bg': foundationColors.white12,
  '--ig-color-toggle-off-border': foundationColors.borderStrong,
  '--ig-color-tab-surface': foundationColors.white04,
  '--ig-color-tab-highlight': foundationColors.blueTint18,
  '--ig-color-toolbar-surface': 'rgba(8, 12, 18, 0.84)',
  '--ig-color-modal-backdrop': foundationColors.overlayBackdrop,
} as const
