import {
  borderWidthScale,
  effectsScale,
  foundationColors,
  foundationColorsLight,
  iconSizes,
  layoutScale,
  popupSizes,
  svgStrokeWidths,
  motionScale,
  opacityScale,
  radiusScale,
  shadowScale,
  shadowScaleLight,
  spacingScale,
  typographyScale,
  zIndexScale,
  controlSizes,
  transformScale,
  aspectRatios,
} from '../core'
import { ingradientThemeDark, ingradientThemeLight } from '../modes'
import type { IngradientTheme } from '../semantic/types'

type Palette = Record<keyof typeof foundationColors, string>
type Shadows = Record<keyof typeof shadowScale, string>

function buildColorVars(theme: IngradientTheme, palette: Palette, shadows: Shadows, isLight: boolean) {
  // For light mode, surface-card / dropdown / toolbar etc. use light tints instead of dark slate
  const lightOnDarkInsetHighlight = isLight
    ? 'rgba(15, 18, 25, 0.04)'
    : 'var(--ig-color-white-04)'
  return {
    // ── Background ────────────────────────────────────────────────
    '--ig-color-bg-canvas': theme.colors.bgCanvas,
    '--ig-color-bg-radial-a': theme.colors.bgRadialA,
    '--ig-color-bg-radial-b': theme.colors.bgRadialB,
    // ── Surface ───────────────────────────────────────────────────
    '--ig-color-surface-header': theme.colors.surfaceHeader,
    '--ig-color-surface-panel': theme.colors.surfacePanel,
    '--ig-color-surface-raised': theme.colors.surfaceRaised,
    '--ig-color-surface-muted': theme.colors.surfaceMuted,
    '--ig-color-surface-interactive': theme.colors.surfaceInteractive,
    '--ig-color-surface-active': theme.colors.surfaceActive,
    // ── Border / Text ─────────────────────────────────────────────
    '--ig-color-border-subtle': theme.colors.borderSubtle,
    '--ig-color-border-strong': theme.colors.borderStrong,
    '--ig-color-text-primary': theme.colors.textPrimary,
    '--ig-color-text-secondary': theme.colors.textSecondary,
    '--ig-color-text-muted': theme.colors.textMuted,
    '--ig-color-text-soft': theme.colors.textSoft,
    // ── Accent / Status ───────────────────────────────────────────
    '--ig-color-accent': theme.colors.accent,
    '--ig-color-accent-strong': theme.colors.accentStrong,
    '--ig-color-accent-soft': theme.colors.accentSoft,
    '--ig-color-success': theme.colors.success,
    '--ig-color-warning': theme.colors.warning,
    '--ig-color-danger': theme.colors.danger,
    '--ig-color-surface-card-a': isLight ? 'rgba(255, 255, 255, 0.96)' : 'rgba(18, 21, 28, 0.96)',
    '--ig-color-surface-card-b': isLight ? 'rgba(247, 249, 251, 0.96)' : 'rgba(10, 14, 20, 0.96)',
    '--ig-color-surface-interactive-hover': palette.white07,
    '--ig-color-surface-focus': isLight ? 'rgba(255, 255, 255, 0.98)' : 'rgba(16, 22, 32, 0.98)',
    '--ig-color-accent-ring': isLight ? 'rgba(58, 115, 230, 0.55)' : 'rgba(91, 144, 255, 0.7)',
    '--ig-color-accent-border-strong': palette.blueTint38,
    '--ig-color-accent-soft-surface': palette.blueTint12,
    '--ig-color-accent-soft-surface-hover': palette.blueTint18,
    '--ig-color-on-accent': '#ffffff', // text/icon over accent-strong button — always white
    '--ig-color-inset-highlight': lightOnDarkInsetHighlight,
    '--ig-shadow-panel': shadows.panel,
    '--ig-shadow-floating': shadows.floating,
    '--ig-shadow-popover': shadows.popover,
    '--ig-shadow-menu': shadows.menu,
    '--ig-shadow-hover-lift': shadows.hoverLift,
    '--ig-shadow-focus-ring': shadows.focusRing,
    '--ig-shadow-drawer-lift': shadows.drawerLift,
    '--ig-shadow-danger-hover-lift': shadows.dangerHoverLift,
    '--ig-shadow-control-elevated': shadows.controlElevated,
    '--ig-scrollbar-thumb': isLight ? 'rgba(15, 23, 42, 0.18)' : 'rgba(148, 163, 184, 0.22)',
    '--ig-scrollbar-thumb-hover': isLight ? 'rgba(15, 23, 42, 0.28)' : 'rgba(148, 163, 184, 0.34)',
    '--ig-scrollbar-thumb-active': isLight ? 'rgba(15, 23, 42, 0.36)' : 'rgba(148, 163, 184, 0.42)',
    '--ig-color-status-running-bg': palette.greenTint18,
    '--ig-color-status-running-text': palette.textSuccess,
    '--ig-color-status-completed-bg': palette.cyanTint18,
    '--ig-color-status-completed-text': palette.textCyan,
    '--ig-color-status-queued-bg': palette.blueTint18,
    '--ig-color-status-queued-text': palette.textBlue,
    '--ig-color-status-draft-bg': palette.amberTint20,
    '--ig-color-status-draft-text': palette.textWarning,
    '--ig-color-status-failed-bg': palette.redTint18,
    '--ig-color-status-failed-text': palette.textDanger,
    '--ig-color-status-stopped-bg': isLight ? 'rgba(15, 23, 42, 0.10)' : 'rgba(148, 163, 184, 0.16)',
    '--ig-color-status-stopped-text': palette.textSlateSoft,
    '--ig-color-status-interrupted-bg': palette.amberTint18,
    '--ig-color-status-interrupted-text': palette.textOrange,
    '--ig-color-status-warning-bg': palette.amberTint18,
    '--ig-color-status-warning-text': palette.textOrange,
    '--ig-color-status-idle-bg': isLight ? 'rgba(15, 23, 42, 0.10)' : 'rgba(67, 76, 94, 0.22)',
    '--ig-color-status-idle-text': palette.textSlate,
    '--ig-color-alert-info-bg': palette.blueTint12,
    '--ig-color-alert-info-border': isLight ? 'rgba(58, 115, 230, 0.32)' : 'rgba(77, 136, 255, 0.26)',
    '--ig-color-alert-info-text': palette.textInfo,
    '--ig-color-alert-success-bg': palette.greenTint12,
    '--ig-color-alert-success-border': isLight ? 'rgba(26, 143, 111, 0.32)' : 'rgba(43, 181, 114, 0.26)',
    '--ig-color-alert-success-text': palette.textSuccessSoft,
    '--ig-color-alert-warning-bg': isLight ? 'rgba(184, 118, 26, 0.12)' : 'rgba(251, 146, 60, 0.12)',
    '--ig-color-alert-warning-border': isLight ? 'rgba(184, 118, 26, 0.32)' : 'rgba(251, 146, 60, 0.26)',
    '--ig-color-alert-warning-text': palette.textWarningSoft,
    '--ig-color-alert-danger-bg': palette.redTint12,
    '--ig-color-alert-danger-border': isLight ? 'rgba(204, 41, 41, 0.32)' : 'rgba(239, 68, 68, 0.26)',
    '--ig-color-alert-danger-text': palette.textDangerSoft,
    '--ig-color-chart-1': palette.blue500,
    '--ig-color-chart-2': palette.green500,
    '--ig-color-chart-3': palette.amber500,
    '--ig-color-chart-4': palette.red300,
    '--ig-color-chart-5': palette.blue300,
    '--ig-color-chart-6': palette.violet300,
    '--ig-color-chart-grid': isLight ? 'rgba(15, 23, 42, 0.08)' : 'var(--ig-color-white-08)',
    '--ig-color-badge-neutral': palette.white08,
    '--ig-color-badge-accent': palette.blueTint18,
    '--ig-color-badge-success': palette.greenTint18,
    '--ig-color-badge-warning': palette.amberTint18,
    '--ig-color-badge-danger': palette.redTint18,
    // Catalog dataset task tags
    '--ig-color-tag-classification-bg': palette.tagClassificationBg,
    '--ig-color-tag-classification-text': palette.tagClassificationText,
    '--ig-color-tag-segmentation-bg': palette.tagSegmentationBg,
    '--ig-color-tag-segmentation-text': palette.tagSegmentationText,
    '--ig-color-tag-object-detection-bg': palette.tagObjectDetectionBg,
    // Sync state chip — opaque variants (image overlay 위에 올라가는 chip)
    '--ig-color-sync-chip-synced-bg': palette.syncChipSyncedBg,
    '--ig-color-sync-chip-uploading-bg': palette.syncChipUploadingBg,
    '--ig-color-sync-chip-failed-bg': palette.syncChipFailedBg,
    '--ig-color-sync-chip-local-bg': palette.syncChipLocalBg,
    '--ig-color-sync-chip-on-text': palette.syncChipOnText,
    // Image card overlay buttons / group count
    '--ig-color-image-option-bg': isLight ? 'rgba(0, 0, 0, 0.5)' : 'rgba(0, 0, 0, 0.6)',
    '--ig-color-image-option-bg-hover': isLight ? 'rgba(0, 0, 0, 0.7)' : 'rgba(0, 0, 0, 0.8)',
    '--ig-color-image-group-circle-bg': palette.imageGroupCircleBg,
    '--ig-color-image-group-circle-border': palette.imageGroupCircleBorder,
    '--ig-color-danger-dim-bg': palette.dangerDimBg,
    '--ig-color-danger-dim-border': palette.dangerDimBorder,
    '--ig-color-progress-track': palette.white08,
    '--ig-color-skeleton-start': palette.white06,
    '--ig-color-skeleton-mid': palette.white12,
    '--ig-color-image-card-hover-border': palette.blueTint28,
    '--ig-color-image-card-selected-border': palette.blueTint42,
    '--ig-color-image-card-selected-ring': palette.blueTint18,
    '--ig-color-image-card-gradient-a': palette.blueTint14,
    '--ig-color-image-card-gradient-b': palette.greenTint12,
    '--ig-color-avatar-bg': palette.blueTint18,
    // Semantic state-interaction aliases — blue tint family 의미 layer
    // (accent-soft-surface = blueTint12, accent-soft-surface-hover = blueTint18 가 이미 존재)
    '--ig-color-selection-bg': palette.blueTint14,
    '--ig-color-focus-bg-soft': palette.blueTint16,
    '--ig-color-active-bg': palette.blueTint28,
    // Status state aliases — red / green / amber / coral tint family 의미 layer
    '--ig-color-danger-bg-soft': 'var(--ig-color-red-tint-08)',
    '--ig-color-danger-bg': 'var(--ig-color-red-tint-12)',
    '--ig-color-danger-bg-hover': 'var(--ig-color-red-tint-18)',
    '--ig-color-danger-bg-strong': 'var(--ig-color-red-tint-60)',
    '--ig-color-danger-overlay': 'var(--ig-color-red-tint-92)',
    '--ig-color-danger-overlay-hover': 'var(--ig-color-red-tint-96)',
    '--ig-color-danger-button-bg': 'var(--ig-color-coral-tint-18)',
    '--ig-color-danger-button-border': 'var(--ig-color-coral-tint-28)',
    '--ig-color-success-bg-soft': 'var(--ig-color-green-tint-08)',
    '--ig-color-success-bg': 'var(--ig-color-green-tint-15)',
    '--ig-color-warning-bg': 'var(--ig-color-amber-tint-15)',
    '--ig-color-dropdown-open-shadow': isLight
      ? '0 0 0 3px rgba(58, 115, 230, 0.20), 0 18px 36px rgba(15, 23, 42, 0.10)'
      : '0 0 0 3px var(--ig-color-blue-tint-16), 0 18px 36px rgba(0, 0, 0, 0.18)',
    '--ig-color-dropdown-menu-a': isLight ? 'rgba(255, 255, 255, 0.98)' : 'rgba(18, 24, 34, 0.98)',
    '--ig-color-dropdown-menu-b': isLight ? 'rgba(247, 249, 251, 0.98)' : 'rgba(10, 14, 20, 0.98)',
    '--ig-color-dropdown-option-hover': palette.white06,
    '--ig-color-toggle-on-bg': isLight ? 'rgba(58, 115, 230, 0.5)' : 'rgba(77, 136, 255, 0.4)',
    '--ig-color-toggle-on-border': isLight ? 'rgba(58, 115, 230, 0.65)' : 'rgba(77, 136, 255, 0.55)',
    '--ig-color-toggle-off-bg': palette.white12,
    '--ig-color-toggle-off-border': palette.borderStrong,
    '--ig-color-tab-surface': palette.white04,
    '--ig-color-tab-highlight': palette.blueTint18,
    '--ig-color-toolbar-surface': isLight ? 'rgba(247, 249, 251, 0.84)' : 'rgba(8, 12, 18, 0.84)',
    '--ig-color-modal-backdrop': palette.overlayBackdrop,
    // Canvas overlay (annotation-toolbar / coord readout 등 어두운 surface)
    '--ig-color-overlay-soft': 'var(--ig-color-overlay-soft)',
    '--ig-color-overlay-dim': 'var(--ig-color-overlay-dim)',
    '--ig-color-overlay-mid': 'var(--ig-color-overlay-mid)',
    '--ig-color-overlay-strong': 'var(--ig-color-overlay-strong)',
    // Lightbox (full-viewport image preview)
    '--ig-color-lightbox-backdrop': 'var(--ig-color-lightbox-backdrop)',
    '--ig-color-lightbox-surface': isLight ? 'rgba(255, 255, 255, 0.7)' : 'rgba(7, 10, 20, 0.7)',
    // Sidebar shell gradient backgrounds
    '--ig-color-sidebar-bg-top': isLight ? 'rgba(247, 249, 251, 0.96)' : 'rgba(12, 15, 20, 0.96)',
    '--ig-color-sidebar-bg-bottom': isLight ? 'rgba(241, 245, 249, 0.94)' : 'rgba(10, 14, 20, 0.94)',
    // Mobile-dropdown gradient backgrounds (dropdown-menu 와 거의 동일, 별도 토큰 분리)
    '--ig-color-surface-dropdown-mobile-top': isLight ? 'rgba(255, 255, 255, 0.98)' : 'rgba(18, 24, 34, 0.98)',
    '--ig-color-surface-dropdown-mobile-bottom': isLight ? 'rgba(247, 249, 251, 0.98)' : 'rgba(10, 14, 20, 0.98)',
    // Date-range-picker (calendar surface) gradient — 살짝 더 투명
    '--ig-color-surface-calendar-top': isLight ? 'rgba(255, 255, 255, 0.96)' : 'rgba(17, 23, 32, 0.96)',
    '--ig-color-surface-calendar-bottom': isLight ? 'rgba(247, 249, 251, 0.96)' : 'rgba(10, 14, 20, 0.96)',
    // Danger button soft surface (toolbar hover)
    '--ig-color-danger-soft-surface': isLight ? 'rgba(220, 38, 38, 0.12)' : 'rgba(164, 44, 44, 0.22)',
    // Danger button gradient + text colors (buttonDanger / buttonDangerSecondary)
    '--ig-color-danger-button-gradient-mid': isLight ? '#a23030' : '#7f1d1d',
    '--ig-color-danger-button-gradient-end': isLight ? '#b13838' : '#8f2f2f',
    '--ig-color-danger-button-text': isLight ? '#ffffff' : '#fff4f4',
    '--ig-color-danger-button-text-strong': isLight ? '#ffffff' : '#ffe1e1',
    // SVG stroke / fill for annotation canvas / chart text on dark overlay
    '--ig-color-svg-stroke-on-overlay': '#ffffff',
    '--ig-color-pie-slice-label': isLight ? '#0f1219' : '#eef4ff',
    // Annotation overlay — bbox/point emphasize outline + halo (canvas 위 항상 dark/light contrast)
    '--ig-color-annotation-outline-dark': 'var(--ig-color-image-option-bg)',
    '--ig-color-annotation-outline-light': 'rgba(255, 255, 255, 0.9)',

    // Direct alpha aliases (consumer raw rgba 마이그레이션 용) — palette-aware
    '--ig-color-white-04': palette.white04,
    '--ig-color-white-06': palette.white06,
    '--ig-color-white-07': palette.white07,
    '--ig-color-white-08': palette.white08,
    '--ig-color-white-10': palette.white10,
    '--ig-color-white-12': palette.white12,
    '--ig-color-white-18': palette.white18,
    '--ig-color-white-20': isLight ? 'rgba(15, 18, 25, 0.16)' : 'rgba(255, 255, 255, 0.2)',
    '--ig-color-white-24': palette.white24,
    '--ig-color-white-30': isLight ? 'rgba(15, 18, 25, 0.22)' : 'rgba(255, 255, 255, 0.3)',
    '--ig-color-white-40': isLight ? 'rgba(15, 18, 25, 0.32)' : 'rgba(255, 255, 255, 0.4)',
    '--ig-color-white-70': isLight ? 'rgba(15, 18, 25, 0.62)' : 'rgba(255, 255, 255, 0.7)',
    '--ig-color-white-90': isLight ? 'rgba(15, 18, 25, 0.82)' : 'rgba(255, 255, 255, 0.9)',
    '--ig-color-slate-tint-18': palette.borderStrong,
    '--ig-color-blue-tint-06': isLight ? 'rgba(58, 115, 230, 0.06)' : 'rgba(77, 136, 255, 0.06)',
    '--ig-color-blue-tint-08': isLight ? 'rgba(58, 115, 230, 0.08)' : 'rgba(77, 136, 255, 0.08)',
    '--ig-color-blue-tint-10': isLight ? 'rgba(58, 115, 230, 0.1)' : 'rgba(77, 136, 255, 0.1)',
    '--ig-color-blue-tint-12': palette.blueTint12,
    '--ig-color-blue-tint-14': palette.blueTint14,
    '--ig-color-blue-tint-15': isLight ? 'rgba(58, 115, 230, 0.15)' : 'rgba(77, 136, 255, 0.15)',
    '--ig-color-blue-tint-16': palette.blueTint16,
    '--ig-color-blue-tint-18': palette.blueTint18,
    '--ig-color-blue-tint-20': isLight ? 'rgba(58, 115, 230, 0.2)' : 'rgba(77, 136, 255, 0.2)',
    '--ig-color-blue-tint-25': isLight ? 'rgba(58, 115, 230, 0.25)' : 'rgba(77, 136, 255, 0.25)',
    '--ig-color-blue-tint-28': palette.blueTint28,
    '--ig-color-blue-tint-35': isLight ? 'rgba(58, 115, 230, 0.35)' : 'rgba(77, 136, 255, 0.35)',
    '--ig-color-blue-tint-38': palette.blueTint38,
    '--ig-color-blue-tint-40': isLight ? 'rgba(58, 115, 230, 0.4)' : 'rgba(77, 136, 255, 0.4)',
    '--ig-color-blue-tint-50': isLight ? 'rgba(58, 115, 230, 0.5)' : 'rgba(77, 136, 255, 0.5)',
    '--ig-color-blue-tint-55': isLight ? 'rgba(58, 115, 230, 0.55)' : 'rgba(77, 136, 255, 0.55)',
    '--ig-color-blue-tint-60': isLight ? 'rgba(58, 115, 230, 0.6)' : 'rgba(77, 136, 255, 0.6)',
    '--ig-color-blue-tint-70': isLight ? 'rgba(58, 115, 230, 0.7)' : 'rgba(77, 136, 255, 0.7)',
    '--ig-color-blue-tint-78': isLight ? 'rgba(58, 115, 230, 0.78)' : 'rgba(77, 136, 255, 0.78)',
    '--ig-color-blue-tint-80': isLight ? 'rgba(58, 115, 230, 0.8)' : 'rgba(77, 136, 255, 0.8)',
    '--ig-color-blue-tint-85': isLight ? 'rgba(58, 115, 230, 0.85)' : 'rgba(77, 136, 255, 0.85)',
    '--ig-color-blue-tint-90': isLight ? 'rgba(58, 115, 230, 0.9)' : 'rgba(77, 136, 255, 0.9)',
    '--ig-color-blue-tint-92': isLight ? 'rgba(58, 115, 230, 0.92)' : 'rgba(77, 136, 255, 0.92)',
    '--ig-color-green-tint-08': isLight ? 'rgba(22, 163, 74, 0.10)' : 'rgba(43, 181, 114, 0.08)',
    '--ig-color-green-tint-15': isLight ? 'rgba(22, 163, 74, 0.18)' : 'rgba(60, 210, 120, 0.15)',
    '--ig-color-amber-tint-15': isLight ? 'rgba(217, 119, 6, 0.18)' : 'rgba(255, 180, 60, 0.15)',
    '--ig-color-red-tint-08': isLight ? 'rgba(220, 38, 38, 0.10)' : 'rgba(239, 68, 68, 0.08)',
    '--ig-color-red-tint-12': isLight ? 'rgba(220, 38, 38, 0.14)' : 'rgba(239, 68, 68, 0.12)',
    '--ig-color-red-tint-18': isLight ? 'rgba(220, 38, 38, 0.20)' : 'rgba(239, 68, 68, 0.18)',
    '--ig-color-coral-tint-18': isLight ? 'rgba(220, 38, 60, 0.20)' : 'rgba(255, 95, 122, 0.18)',
    '--ig-color-coral-tint-28': isLight ? 'rgba(220, 38, 60, 0.30)' : 'rgba(255, 95, 122, 0.28)',
    '--ig-color-blue-tint-62': isLight ? 'rgba(58, 115, 230, 0.62)' : 'rgba(77, 136, 255, 0.62)',
    '--ig-color-blue-tint-34': isLight ? 'rgba(58, 115, 230, 0.34)' : 'rgba(77, 136, 255, 0.34)',
    '--ig-color-blue-strong-tint-20': isLight ? 'rgba(20, 63, 166, 0.2)' : 'rgba(41, 98, 217, 0.2)',
    '--ig-color-blue-strong-tint-24': isLight ? 'rgba(20, 63, 166, 0.24)' : 'rgba(41, 98, 217, 0.24)',
    '--ig-color-blue-strong-tint-30': isLight ? 'rgba(20, 63, 166, 0.3)' : 'rgba(41, 98, 217, 0.3)',
    '--ig-color-red-tint-92': isLight ? 'rgba(220, 38, 38, 0.92)' : 'rgba(239, 68, 68, 0.92)',
    '--ig-color-red-tint-96': isLight ? 'rgba(185, 28, 28, 0.96)' : 'rgba(220, 38, 38, 0.96)',
    '--ig-color-slate-tint-86': isLight ? 'rgba(229, 231, 235, 0.86)' : 'rgba(75, 85, 99, 0.86)',
    '--ig-color-white-32': isLight ? 'rgba(15, 18, 25, 0.24)' : 'rgba(255, 255, 255, 0.32)',
    '--ig-color-white-35': isLight ? 'rgba(15, 18, 25, 0.27)' : 'rgba(255, 255, 255, 0.35)',
    '--ig-color-white-45': isLight ? 'rgba(15, 18, 25, 0.37)' : 'rgba(255, 255, 255, 0.45)',
    '--ig-color-white-55': isLight ? 'rgba(15, 18, 25, 0.47)' : 'rgba(255, 255, 255, 0.55)',
    '--ig-color-white-62': isLight ? 'rgba(15, 18, 25, 0.54)' : 'rgba(255, 255, 255, 0.62)',
    '--ig-color-white-80': isLight ? 'rgba(15, 18, 25, 0.72)' : 'rgba(255, 255, 255, 0.8)',
    '--ig-color-overlay-darker': isLight ? 'rgba(0, 0, 0, 0.48)' : 'rgba(0, 0, 0, 0.65)',
    '--ig-color-overlay-darkest': isLight ? 'rgba(0, 0, 0, 0.62)' : 'rgba(0, 0, 0, 0.82)',
    '--ig-color-overlay-near-opaque': isLight ? 'rgba(0, 0, 0, 0.72)' : 'rgba(0, 0, 0, 0.92)',
    '--ig-color-capture-surface-loud': isLight ? 'rgba(229, 231, 235, 0.86)' : 'rgba(17, 24, 39, 0.86)',
    '--ig-color-capture-surface': isLight ? 'rgba(229, 231, 235, 0.7)' : 'rgba(17, 24, 39, 0.7)',
    '--ig-color-capture-overlay': isLight ? 'rgba(0, 0, 0, 0.24)' : 'rgba(0, 0, 0, 0.36)',
    '--ig-color-app-backdrop': isLight ? 'rgba(0, 0, 0, 0.22)' : 'rgba(0, 0, 0, 0.32)',
    '--ig-color-yellow-tint-50': isLight ? 'rgba(202, 138, 4, 0.5)' : 'rgba(255, 255, 0, 0.5)',
    '--ig-color-slate-gray-tint-12': isLight ? 'rgba(71, 85, 105, 0.12)' : 'rgba(127, 139, 157, 0.12)',
    '--ig-color-slate-gray-tint-16': isLight ? 'rgba(71, 85, 105, 0.16)' : 'rgba(127, 139, 157, 0.16)',
    '--ig-color-slate-gray-tint-18': isLight ? 'rgba(71, 85, 105, 0.18)' : 'rgba(127, 139, 157, 0.18)',
    '--ig-color-red-tint-60': isLight ? 'rgba(220, 38, 38, 0.6)' : 'rgba(239, 68, 68, 0.6)',
    '--ig-color-red-tint-15': isLight ? 'rgba(220, 38, 38, 0.18)' : 'rgba(239, 68, 68, 0.15)',
    '--ig-color-overlay-deep': isLight ? 'rgba(0, 0, 0, 0.58)' : 'rgba(0, 0, 0, 0.78)',
    '--ig-color-capture-bg-loud': isLight ? 'rgba(229, 231, 235, 0.82)' : 'rgba(12, 16, 22, 0.82)',
    '--ig-color-blue-accent-solid': isLight ? 'rgba(58, 115, 230, 1)' : 'rgba(77, 136, 255, 1)',
    '--ig-color-surface-dropdown-grid-top': isLight ? 'rgba(255, 255, 255, 0.98)' : 'rgba(18, 24, 34, 0.98)',
    '--ig-color-surface-dropdown-grid-bottom': isLight ? 'rgba(247, 249, 251, 0.98)' : 'rgba(12, 16, 24, 0.98)',
    '--ig-color-green-tint-success-soft': isLight ? 'rgba(22, 163, 74, 0.08)' : 'rgba(52, 211, 153, 0.06)',
    '--ig-color-amber-tint-warning-soft': isLight ? 'rgba(217, 119, 6, 0.08)' : 'rgba(250, 204, 21, 0.06)',
    '--ig-color-project-tag-general': isLight ? 'rgba(71, 85, 105, 0.92)' : 'rgba(100, 116, 139, 0.92)',
    '--ig-color-project-tag-deflectometry': isLight ? 'rgba(2, 132, 199, 0.92)' : 'rgba(14, 165, 233, 0.92)',
  } as const
}

// Theme-independent vars (radius / spacing / typography / z / control sizes)
const staticVars = {
  // ── Radius (2xs:6 → 4xl:24, plus pill) ────────────────────────
  '--ig-radius-2xs': radiusScale['2xs'],
  '--ig-radius-xxs': radiusScale.xxs,
  '--ig-radius-xs': radiusScale.xs,
  '--ig-radius-sm': ingradientThemeDark.radius.sm,
  '--ig-radius-md': ingradientThemeDark.radius.md,
  '--ig-radius-lg': ingradientThemeDark.radius.lg,
  '--ig-radius-xl': ingradientThemeDark.radius.xl,
  '--ig-radius-2xl': radiusScale['2xl'],
  '--ig-radius-4xl': radiusScale['4xl'],
  '--ig-radius-pill': ingradientThemeDark.radius.pill,
  // ── Typography ────────────────────────────────────────────────
  '--ig-font-sans': ingradientThemeDark.typography.fontSans,
  '--ig-font-mono': ingradientThemeDark.typography.fontMono,
  '--ig-font-size-3xs': typographyScale.size3xs,
  '--ig-font-size-2xs': typographyScale.size2xs,
  '--ig-font-size-xs': typographyScale.sizeXs,
  '--ig-font-size-sm': typographyScale.sizeSm,
  '--ig-font-size-md': typographyScale.sizeMd,
  '--ig-font-size-lg': typographyScale.sizeLg,
  '--ig-font-size-xl': typographyScale.sizeXl,
  '--ig-font-size-2xl': typographyScale.size2xl,
  '--ig-font-size-3xl': typographyScale.size3xl,
  '--ig-font-size-3xl-plus': typographyScale.size3xlPlus,
  '--ig-font-size-4xl': typographyScale.size4xl,
  '--ig-font-size-5xl': typographyScale.size5xl,
  '--ig-font-weight-regular': String(typographyScale.weightRegular),
  '--ig-font-weight-medium': String(typographyScale.weightMedium),
  '--ig-font-weight-semibold': String(typographyScale.weightSemibold),
  '--ig-font-weight-bold': String(typographyScale.weightBold),
  '--ig-font-weight-black': String(typographyScale.weightBlack),
  '--ig-letter-spacing-heading': typographyScale.letterSpacingHeading,
  '--ig-letter-spacing-micro': typographyScale.letterSpacingMicro,
  '--ig-letter-spacing-tight': typographyScale.letterSpacingTight,
  '--ig-letter-spacing-normal': typographyScale.letterSpacingNormal,
  '--ig-letter-spacing-wide': typographyScale.letterSpacingWide,
  '--ig-letter-spacing-wider': typographyScale.letterSpacingWider,
  '--ig-letter-spacing-widest': typographyScale.letterSpacingWidest,
  '--ig-line-height-none': String(typographyScale.lineHeightNone),
  '--ig-line-height-tight': String(typographyScale.lineHeightTight),
  '--ig-line-height-snug': String(typographyScale.lineHeightSnug),
  '--ig-line-height-base': String(typographyScale.lineHeightBase),
  '--ig-line-height-relaxed': String(typographyScale.lineHeightRelaxed),
  '--ig-line-height-loose': String(typographyScale.lineHeightLoose),
  '--ig-opacity-hidden': String(opacityScale.hidden),
  '--ig-opacity-ghost': String(opacityScale.ghost),
  '--ig-opacity-faded': String(opacityScale.faded),
  '--ig-opacity-disabled': String(opacityScale.disabled),
  '--ig-opacity-overlay': String(opacityScale.overlay),
  '--ig-opacity-muted': String(opacityScale.muted),
  '--ig-opacity-subtle': String(opacityScale.subtle),
  '--ig-opacity-emphatic': String(opacityScale.emphatic),
  '--ig-opacity-loud': String(opacityScale.loud),
  '--ig-opacity-prominent': String(opacityScale.prominent),
  '--ig-opacity-near': String(opacityScale.near),
  '--ig-blur-2xs': effectsScale.blur2xs,
  '--ig-blur-xs': effectsScale.blurXs,
  '--ig-blur-sm': effectsScale.blurSm,
  '--ig-blur-md': effectsScale.blurMd,
  '--ig-blur-lg': effectsScale.blurLg,
  '--ig-blur-xl': effectsScale.blurXl,
  '--ig-icon-xs': iconSizes.xs,
  '--ig-icon-sub': iconSizes.sub,
  '--ig-icon-2xs': iconSizes['2xs'],
  '--ig-icon-sm': iconSizes.sm,
  '--ig-icon-sm-plus': iconSizes.smPlus,
  '--ig-icon-xs-plus': iconSizes.xsPlus,
  '--ig-icon-md': iconSizes.md,
  '--ig-icon-lg': iconSizes.lg,
  '--ig-icon-xl': iconSizes.xl,
  '--ig-icon-2xl': iconSizes['2xl'],
  '--ig-icon-3xl': iconSizes['3xl'],
  // CSS var() 는 SVG attribute 에 적용 불가 — SVG 안에서는 svgStrokeWidths TS const 사용.
  // CSS 안 stroke-width 용으로만 bold 1개 유지 (toggles checkbox SVG mask).
  '--ig-svg-stroke-bold': String(svgStrokeWidths.bold),
  '--ig-popup-3xs': popupSizes['3xs'],
  '--ig-popup-2xs': popupSizes['2xs'],
  '--ig-popup-2xs-plus': popupSizes['2xsPlus'],
  '--ig-popup-xs': popupSizes.xs,
  '--ig-popup-sm': popupSizes.sm,
  '--ig-popup-md': popupSizes.md,
  '--ig-popup-lg': popupSizes.lg,
  '--ig-popup-xl': popupSizes.xl,
  '--ig-popup-2xl-narrow': popupSizes['2xlNarrow'],
  '--ig-popup-2xl': popupSizes['2xl'],
  '--ig-popup-3xl': popupSizes['3xl'],
  '--ig-popup-log-filter': popupSizes.logFilter,
  '--ig-popup-2xl-wide': popupSizes['2xlWide'],
  '--ig-popup-3xl-narrow': popupSizes['3xlNarrow'],
  '--ig-popup-3xl-mid': popupSizes['3xlMid'],
  '--ig-popup-3xl-wide': popupSizes['3xlWide'],
  '--ig-popup-4xl-narrow': popupSizes['4xlNarrow'],
  '--ig-popup-4xl': popupSizes['4xl'],
  '--ig-popup-list-min': popupSizes.listMin,
  '--ig-popup-class-sidebar': popupSizes.classSidebar,
  '--ig-popup-catalog-card': popupSizes.catalogCard,
  '--ig-popup-dialog-sidebar': popupSizes.dialogSidebar,
  '--ig-popup-page-card-min': popupSizes.pageCardMin,
  '--ig-popup-icon-gallery-min': popupSizes.iconGalleryMin,
  '--ig-icon-gallery-min': popupSizes.iconGalleryMin,
  '--ig-popup-license-narrow': popupSizes.licenseNarrow,
  '--ig-space-0': spacingScale[0],
  '--ig-space-1px': spacingScale['1px'],
  '--ig-space-2px': spacingScale['2px'],
  '--ig-space-3px': spacingScale['3px'],
  '--ig-space-neg-1px': spacingScale['-1px'],
  '--ig-space-neg-2px': spacingScale['-2px'],
  '--ig-space-neg-4': spacingScale['-4'],
  '--ig-transform-hover-lift-y': spacingScale.hoverLiftY,
  '--ig-space-1': spacingScale[1],
  '--ig-space-1-plus': spacingScale['1Plus'],
  '--ig-space-2': spacingScale[2],
  '--ig-space-2-plus': spacingScale['2Plus'],
  '--ig-space-3': spacingScale[3],
  '--ig-space-4': spacingScale[4],
  '--ig-space-5': spacingScale[5],
  '--ig-space-6': spacingScale[6],
  '--ig-space-7': spacingScale[7],
  '--ig-space-8': spacingScale[8],
  '--ig-space-9': spacingScale[9],
  '--ig-space-10': spacingScale[10],
  '--ig-space-11': spacingScale[11],
  '--ig-space-12': spacingScale[12],
  '--ig-space-13': spacingScale[13],
  '--ig-border-1px': borderWidthScale['1px'],
  '--ig-border-2px': borderWidthScale['2px'],
  '--ig-border-3px': borderWidthScale['3px'],
  '--ig-z-hidden': String(zIndexScale.hidden),
  '--ig-z-base': String(zIndexScale.base),
  '--ig-z-raised': String(zIndexScale.raised),
  '--ig-z-raised-plus': String(zIndexScale.raisedPlus),
  '--ig-z-capture': String(zIndexScale.capture),
  '--ig-z-capture-high': String(zIndexScale.captureHigh),
  '--ig-z-capture-super': String(zIndexScale.captureSuper),
  '--ig-z-capture-top': String(zIndexScale.captureTop),
  '--ig-z-sticky': String(zIndexScale.sticky),
  '--ig-z-sticky-plus': String(zIndexScale.stickyPlus),
  '--ig-z-sticky-top': String(zIndexScale.stickyTop),
  '--ig-z-header': String(zIndexScale.header),
  '--ig-z-overlay': String(zIndexScale.overlay),
  '--ig-z-overlay-low': String(zIndexScale.overlayLow),
  '--ig-z-dot-menu': String(zIndexScale.dotMenu),
  '--ig-z-dot-menu-plus': String(zIndexScale.dotMenuPlus),
  '--ig-z-topbar': String(zIndexScale.topbar),
  '--ig-z-dropdown': String(zIndexScale.dropdown),
  '--ig-z-mobile-nav-backdrop': String(zIndexScale.mobileNavBackdrop),
  '--ig-z-mobile-nav': String(zIndexScale.mobileNav),
  '--ig-z-mobile-menu': String(zIndexScale.mobileMenu),
  '--ig-z-popover': String(zIndexScale.popover),
  '--ig-z-context-menu': String(zIndexScale.contextMenu),
  '--ig-z-drawer': String(zIndexScale.drawer),
  '--ig-z-modal': String(zIndexScale.modal),
  '--ig-z-toast': String(zIndexScale.toast),
  '--ig-z-tooltip': String(zIndexScale.tooltip),
  '--ig-scale-press': String(transformScale.press),
  '--ig-scale-drag': String(transformScale.drag),
  '--ig-scale-hover-lift': String(transformScale.hoverLift),
  '--ig-aspect-square': aspectRatios.square,
  '--ig-aspect-landscape': aspectRatios.landscape,
  '--ig-aspect-wide': aspectRatios.wide,
  '--ig-aspect-ultra-wide': aspectRatios.ultraWide,
  '--ig-aspect-portrait': aspectRatios.portrait,
  '--ig-control-height-xs': controlSizes.xs,
  '--ig-control-height-xs-plus': controlSizes.xsPlus,
  '--ig-control-height-sm': controlSizes.sm,
  '--ig-control-height-sm-plus': controlSizes.smPlus,
  '--ig-control-height-md': controlSizes.md,
  '--ig-control-height-mid-plus': controlSizes.midPlus,
  '--ig-control-height-mid-plus-tall': controlSizes.midPlusTall,
  '--ig-control-height-2xl-wide': controlSizes['2xlWide'],
  '--ig-control-height-lg': controlSizes.lg,
  '--ig-control-height-xl': controlSizes.xl,
  '--ig-control-height-2xl': controlSizes['2xl'],
  '--ig-control-height-3xl': controlSizes['3xl'],
  '--ig-control-height-capture': controlSizes.capture,
  '--ig-page-max-width': layoutScale.pageMaxWidth,
  '--ig-layout-topbar': layoutScale.topbarHeight,
  '--ig-layout-capture-bar': layoutScale.captureBar,
  '--ig-layout-capture-grid': layoutScale.captureGrid,
  '--ig-layout-histogram-width': layoutScale.histogramWidth,
  '--ig-layout-histogram-height': layoutScale.histogramHeight,
  '--ig-layout-dataset-card-min-height': layoutScale.datasetCardMinHeight,
  '--ig-layout-dataset-card-recent-min-height': layoutScale.datasetCardRecentMinHeight,
  '--ig-layout-log-time-min': layoutScale.logTimeMin,
  '--ig-layout-log-detail-left': layoutScale.logDetailLeft,
  '--ig-layout-log-detail-top': layoutScale.logDetailTop,
  '--ig-layout-log-detail-width': layoutScale.logDetailWidth,
  '--ig-space-modal-shadow-y': layoutScale.modalShadowY,
  '--ig-space-modal-shadow-blur': layoutScale.modalShadowBlur,
  '--ig-layout-sidebar-brand': layoutScale.sidebarBrand,
  '--ig-layout-sidebar-collapse-threshold': layoutScale.sidebarCollapseThreshold,
  '--ig-layout-stats-min': layoutScale.statsMin,
  '--ig-layout-loading-stats': layoutScale.loadingStats,
  '--ig-grid-label-col': layoutScale.gridLabelCol,
  '--ig-grid-label-col-wide': layoutScale.gridLabelColWide,
  '--ig-motion-fastest': motionScale.fastest,
  '--ig-motion-swift': motionScale.swift,
  '--ig-motion-fast': motionScale.fast,
  '--ig-motion-fast-ease': motionScale.fastEase,
  '--ig-motion-normal': motionScale.normal,
  '--ig-motion-normal-ease': motionScale.normalEase,
  '--ig-motion-mobile-nav': motionScale.mobileNav,
  '--ig-motion-slow': motionScale.slow,
  '--ig-motion-spinner': motionScale.spinner,
  '--ig-motion-spinner-fast': motionScale.spinnerFast,
  '--ig-motion-spinner-slow': motionScale.spinnerSlow,
  '--ig-motion-progress-bar': motionScale.progressBar,
  '--ig-motion-sync-spin': motionScale.syncSpin,
  '--ig-motion-shimmer': motionScale.shimmer,
  '--ig-motion-skeleton': motionScale.skeleton,
} as const

export function buildTokenCssVariables(mode: 'dark' | 'light' = 'dark') {
  const theme = mode === 'light' ? ingradientThemeLight : ingradientThemeDark
  const palette = mode === 'light' ? foundationColorsLight : foundationColors
  const shadows = mode === 'light' ? shadowScaleLight : shadowScale
  return {
    ...staticVars,
    ...buildColorVars(theme, palette, shadows, mode === 'light'),
  }
}

// Backward-compat default export — dark mode css vars (existing callers).
export const tokenCssVariables = buildTokenCssVariables('dark')
