export const layoutScale = {
  pageMaxWidth: '1280px',
  topbarHeight: '80px',
  captureBar: '100px',
  captureGrid: '100px',
  histogramWidth: '224px',
  histogramHeight: '84px',
  datasetCardMinHeight: '112px',
  datasetCardRecentMinHeight: '108px',
  logTimeMin: '45px',
  logDetailLeft: '254px',
  logDetailTop: '58px',
  logDetailWidth: '272px',
  modalShadowY: '40px',
  modalShadowBlur: '80px',
  sidebarBrand: '72px',
  sidebarCollapseThreshold: '100px',
  statsMin: '300px',
  loadingStats: '180px',
  gridLabelCol: '140px',
  gridLabelColWide: '160px',
} as const
