export const typographyScale = {
  fontSans: '"IBM Plex Sans", "Segoe UI", sans-serif',
  fontMono: '"IBM Plex Mono", "SFMono-Regular", Consolas, monospace',
  size3xs: '10px',
  size2xs: '11px',
  sizeXs: '12px',
  sizeSm: '13px',
  sizeMd: '14px',
  sizeLg: '15px',
  sizeXl: '16px',
  size2xl: '18px',
  size3xl: '20px',
  size3xlPlus: '22px',
  size4xl: '24px',
  size5xl: '28px',
  weightRegular: 400,
  weightMedium: 500,
  weightSemibold: 600,
  weightBold: 700,
  weightBlack: 800,
  letterSpacingHeading: '-0.02em',
  letterSpacingMicro: '0.01em',
  letterSpacingTight: '0.03em',
  letterSpacingNormal: '0.04em',
  letterSpacingWide: '0.05em',
  letterSpacingWider: '0.06em',
  letterSpacingWidest: '0.08em',
  lineHeightNone: 1,
  lineHeightTight: 1.35,
  lineHeightSnug: 1.4,
  lineHeightBase: 1.45,
  lineHeightRelaxed: 1.5,
  lineHeightLoose: 1.6,
} as const
