import {
  Activity,
  AlertCircle,
  BarChart3,
  Camera,
  CheckCircle,
  ChevronRight,
  FileText,
  Filter,
  Globe,
  Grid3X3,
  ImageIcon,
  Info,
  Layers,
  LayoutGrid,
  LineChart as LineChartGlyph,
  Maximize,
  PieChart as PieChartGlyph,
  QrCode,
  RefreshCw,
  Search,
  Settings,
  Shuffle,
  Table2,
  Wifi,
  WifiOff,
  X,
} from 'lucide-react'

export const icons = {
  activity: Activity,
  alertCircle: AlertCircle,
  barChart3: BarChart3,
  camera: Camera,
  checkCircle: CheckCircle,
  chevronRight: ChevronRight,
  fileText: FileText,
  filter: Filter,
  globe: Globe,
  grid3x3: Grid3X3,
  image: ImageIcon,
  info: Info,
  layers: Layers,
  layoutGrid: LayoutGrid,
  lineChart: LineChartGlyph,
  maximize: Maximize,
  pieChart: PieChartGlyph,
  qrCode: QrCode,
  refreshCw: RefreshCw,
  search: Search,
  settings: Settings,
  shuffle: Shuffle,
  table: Table2,
  wifi: Wifi,
  wifiOff: WifiOff,
  x: X,
} as const

export type IconName = keyof typeof icons
